# First stage document build
FROM sphinxdoc/sphinx AS builder

RUN  apt-get -y update \
     && apt-get -y autoremove \
     && apt-get clean \
     && apt-get install -y zip \
     && rm -rf /var/lib/apt/lists/*

COPY requirements_docker_docs.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY /docs/user_guide/ /docs/user_guide/

# Build the multipage HTML documents
RUN sphinx-build -M html /docs/user_guide/source/ /docs/user_guide/build/
# Create a zipped website
RUN zip -r /docs/user_guide/build/help /docs/user_guide/build/html
# Build the PDF document
RUN sphinx-build -M rinoh /docs/user_guide/source/ /docs/user_guide/build/

# Second stage document delivery
FROM httpd:2.4-alpine

RUN mkdir /usr/local/apache2/htdocs/docs
# Copy the website and other documents from the 1st stage image
COPY --from=builder /docs/user_guide/build/html/ /usr/local/apache2/htdocs/
COPY --from=builder /docs/user_guide/build/help.zip /usr/local/apache2/htdocs/docs/.
COPY --from=builder /docs/user_guide/build/rinoh/crag_user_guide.pdf /usr/local/apache2/htdocs/docs/.
