name: fdc
channels:
  - https://nexus-internal.bgs.ac.uk/repository/conda/main
  - https://nexus-internal.bgs.ac.uk/repository/conda-forge
dependencies:
  # Correspond to current long-term support versions in Windows
  - python=3.9
  - pip=23.2
  - qgis=3.28
  - pip:
      - eralchemy
      - etlhelper
      - flake8
      - ipdb
      - ipython
      - pb_tool
      - pytest
      - sqlalchemy<1.4
      - sqlparse
