name: fdc
channels:
  - https://nexus-internal.bgs.ac.uk/repository/conda-forge
dependencies:
  # Correspond to current long-term support versions in Windows
  - python=3.12
  - qgis=3.40

  - beautifulsoup4
  - eralchemy2
  - exifread
  - flake8
  - ipdb
  - ipython
  - Jinja2
  - lxml
  - pandas
  - pillow
  - pip  # Required to make sure that conda uses the correct pip
  - pytest
  - rdflib
  - reportlab
  - sqlalchemy
  - pypdf

  - pip:
      - etlhelper
      - mergin-client
      - pb_tool
