BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "simple_lithology_categories" (
	"simple_lithology_category"	INTEGER,
	"simple_lithology"	TEXT
);
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('acidic igneous rock','acidic igneous material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('acidic igneous rock','acidic igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','alkali feldspar granite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('rhyolitoid','alkali feldspar rhyolite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','alkali feldspar syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','alkali feldspar syenitic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','alkali feldspar trachyte');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','alkali feldspar trachytic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('basalt','alkali olivine basalt');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('amphibolite','amphibolite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('andesite','andesite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('anorthositic rock','anorthosite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('anorthositic rock','anorthositic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary rock','anthracite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('anthropogenic material','anthropogenic material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('anthropogenic material','anthropogenic unconsolidated material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('rock','aphanite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('phaneritic igneous rock','aplite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic sandstone','arenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','ash and lapilli');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','ash breccia bomb or block tephra');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','ash tuff lapillistone and lapilli tuff');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('basalt','basalt');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','basanite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','basanitic foidite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('basic igneous rock','basic igneous material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('basic igneous rock','basic igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('material formed in surficial environment','bauxite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('biogenic sediment','biogenic sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary rock','biogenic silica sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary rock','bituminous coal');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('andesite','boninite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','boulder gravel size sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','boundstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('breccia','breccia');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fault related material','breccia gouge series');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','calcareous carbonate sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','calcareous carbonate sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','calcareous carbonate sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','carbonate mud');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','carbonate mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','carbonate ooze');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','carbonate rich mud');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','carbonate rich mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','carbonate sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','carbonate sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','carbonate sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','carbonate wackestone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('exotic composition igneous rock','carbonatite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fault related material','cataclasite series');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','chalk');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','chemical sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chlorite actinolite epidote metamorphic rock','chlorite actinolite epidote metamorphic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','clastic sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','clastic sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary rock','clastic sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','clay');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','claystone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary rock','coal');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','cobble gravel size sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('composite genesis material','composite genesis material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('composite genesis material','composite genesis rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('compound material','compound material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic conglomerate','conglomerate');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','crystalline carbonate');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','dacite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary rock','diamictite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','diamicton');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','diorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','dioritic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','dioritoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('igneous rock','doleritic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dolomitic or magnesian sedimentary rock','dolomite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','dolomitic or magnesian sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dolomitic or magnesian sedimentary rock','dolomitic or magnesian sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','dolomitic sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('material formed in surficial environment','duricrust');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('eclogite','eclogite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','evaporite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('exotic composition igneous rock','exotic alkaline rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('exotic composition igneous rock','exotic composition igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','exotic evaporite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fault related material','fault related material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','fine grained igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','foid bearing alkali feldspar syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','foid bearing alkali feldspar trachyte');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('anorthositic rock','foid bearing anorthosite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','foid bearing diorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','foid bearing gabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','foid bearing latite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','foid bearing monzodiorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','foid bearing monzogabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','foid bearing monzonite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','foid bearing syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','foid bearing trachyte');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','foid diorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','foid dioritoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','foid gabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','foid gabbroid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','foid monzodiorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','foid monzogabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','foid monzosyenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','foid syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','foid syenitoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','foidite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','foiditoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('phaneritic igneous rock','foidolite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('foliated metamorphic rock','foliated metamorphic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','fragmental igneous material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','fragmental igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','framestone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','gabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','gabbroic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','gabbroid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic conglomerate','generic conglomerate');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','generic mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic sandstone','generic sandstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('igneous rock','glass rich igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('igneous rock','glassy igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('glaucophane lawsonite epidote metamorphic rock','glaucophane lawsonite epidote metamorphic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gneiss','gneiss');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','grainstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','granite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','granitoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','granodiorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granofels','granofels');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granulite','granulite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','gravel');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','gravel size sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','gypsum or anhydrite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','high magnesium fine grained igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('ultramafic igneous rock','hornblendite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granofels','hornfels');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','hybrid sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary rock','hybrid sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('igneous rock','igneous material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('igneous rock','igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('impact generated material','impact generated material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','impure calcareous carbonate sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','impure carbonate sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','impure carbonate sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dolomitic or magnesian sedimentary rock','impure dolomite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','impure dolomitic sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','impure limestone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('intermediate composition igneous rock','intermediate composition igneous material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('intermediate composition igneous rock','intermediate composition igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','iron rich sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','iron rich sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary rock','iron rich sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('exotic composition igneous rock','kalsilitic and melilitic rocks');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('ultramafic igneous rock','komatiitic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','latite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','latitic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary rock','lignite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','limestone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('marble','marble');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('material formed in surficial environment','material formed in surficial environment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('metamorphic rock','metamorphic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('metasomatic rock','metasomatic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('schist','mica schist');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('migmatite','migmatite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','monzodiorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','monzodioritic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','monzogabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','monzogabbroic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','monzogranite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','monzonite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','monzonitic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','mud');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','mud size sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fault related material','mylonitic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('natural unconsolidated material','natural unconsolidated material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','non clastic siliceous sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','non clastic siliceous sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary rock','non clastic siliceous sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('biogenic sediment','ooze');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','organic bearing mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary material','organic rich sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary material','organic rich sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary rock','organic rich sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gneiss','orthogneiss');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','packstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gneiss','paragneiss');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary material','peat');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','pebble gravel size sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('phaneritic igneous rock','pegmatite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('ultramafic igneous rock','peridotite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('phaneritic igneous rock','phaneritic igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','phonolite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','phonolitic basanite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','phonolitic foidite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','phonolitic tephrite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','phonolitoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','phosphate rich sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','phosphate rich sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary rock','phosphorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('phyllite','phyllite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fault related material','phyllonite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('igneous rock','porphyry');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','pure calcareous carbonate sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','pure carbonate mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','pure carbonate sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','pure carbonate sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary material','pure dolomitic sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','pyroclastic material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','pyroclastic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('ultramafic igneous rock','pyroxenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','quartz alkali feldspar syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','quartz alkali feldspar trachyte');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('anorthositic rock','quartz anorthosite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','quartz diorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','quartz gabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','quartz latite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('dioritoid','quartz monzodiorite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('gabbroid','quartz monzogabbro');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','quartz monzonite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('acidic igneous rock','quartz rich igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','quartz syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','quartz trachyte');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('quartzite','quartzite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('material formed in surficial environment','residual material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('rhyolitoid','rhyolite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('rhyolitoid','rhyolitoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('rock','rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('chemical sedimentary material','rock salt');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','sand');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','sand size sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic sandstone','sandstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('organic rich sedimentary material','sapropel');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('schist','schist');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','sediment');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','sedimentary material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary rock','sedimentary rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('serpentinite','serpentinite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','shale');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('sedimentary material','silicate mud');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','silicate mudstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('biogenic sediment','siliceous ooze');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('clastic sedimentary material','silt');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic mudstone','siltstone');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('metasomatic rock','skarn');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('slate','slate');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('metasomatic rock','spilite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','syenite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','syenitic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('syenitoid','syenitoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','syenogranite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','tephra');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','tephrite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','tephritic foidite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','tephritic phonolite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','tephritoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('basalt','tholeiitic basalt');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('granitoid','tonalite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','trachyte');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','trachytic rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('fine grained igneous rock','trachytoid');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('carbonate sedimentary rock','travertine');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','tuff breccia agglomerate or pyroclastic breccia');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('pyroclastic material','tuffite');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('ultramafic igneous rock','ultrabasic igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('ultramafic igneous rock','ultramafic igneous rock');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('unconsolidated material','unconsolidated material');
INSERT INTO "simple_lithology_categories" ("simple_lithology_category","simple_lithology") VALUES ('generic sandstone','wacke');
COMMIT;
