CREATE TABLE "dic_mapped_scale" (
	"fid"	INTEGER NOT NULL,
	"code"  TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_geol_line_theme_cat" (
	"fid"	INTEGER NOT NULL,
	"theme"	TEXT NOT NULL UNIQUE,
    "category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_compass" (
	"fid"	INTEGER NOT NULL,
    "code"  TEXT NOT NULL UNIQUE,
	"abbrev" TEXT NOT NULL UNIQUE,
    "description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_deformation_episode" (
	"fid"	INTEGER NOT NULL,
    "CODE"  TEXT NOT NULL UNIQUE,
	"abbrev"	TEXT NOT NULL UNIQUE,
    "category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"status"    TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
)CREATE TABLE "dic_mineral" (
	"fid"	INTEGER NOT NULL,
	"code" TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_min_vein" (
	"fid"	INTEGER NOT NULL,
	"code" TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_line_type_artificial" (
	"fid"	INTEGER NOT NULL,
	"line_type"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
    "status"	TEXT,
  	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_line_type_superficial" (
	"fid"	INTEGER NOT NULL,
	"line_type"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"mapped_scale"  TEXT,
    "status"	TEXT,
    "user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_line_type_terrain" (
	"fid"	INTEGER NOT NULL,
	"line_type"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"mapped_scale"  TEXT,
	"status"	TEXT,
    "sec_attrib_list"  TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_line_type_bedrock" (
    "fid"	INTEGER NOT NULL,
	"line_type"	TEXT NOT NULL UNIQUE,
    "description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
    "status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "dic_line_type_mass_move" (
    "fid"	INTEGER NOT NULL,
	"line_type"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "artificial_line" (
    "fid" INTEGER NOT NULL,
    "objectid" INTEGER UNIQUE,
    "uuid" TEXT NOT NULL UNIQUE,
    "geol_theme" TEXT NOT NULL,
    "geol_theme_category" TEXT NOT NULL,
    "line_type" TEXT NOT NULL,
    "is_boundary_yn" TEXT,
    "mapped_scale"  TEXT,
 	"comments" TEXT,   
    "status" TEXT DEFAULT "C" NOT NULL,
    "user_entered" TEXT NOT NULL,
    "date_entered" DATETIME NOT NULL,
    "user_updated" TEXT,
    "date_updated" DATETIME,
    FOREIGN KEY("line_type_code") REFERENCES "dic_line_type_artificial"("line_type"),
    FOREIGN KEY("geol_theme") REFERENCES "dic_geol_theme_cat"("theme"),
    FOREIGN KEY("geol_theme_category") REFERENCES "dic_geol_theme_cat"("category"),
    PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "bedrock_line" (
    "fid" INTEGER NOT NULL,
    "objectid" INTEGER UNIQUE,
    "uuid" TEXT NOT NULL UNIQUE,
    "geol_theme" TEXT NOT NULL,
    "geol_theme_category" TEXT NOT NULL,
    "line_type" TEXT NOT NULL,
    "hang_wall_dir" TEXT DEFAULT "?" NOT NULL,
    "young_dir" TEXT DEFAULT "?" NOT NULL
    "line_name" TEXT,
    "mineral" TEXT DEFAULT "?" NOT NULL,
    "min_vein01" TEXT DEFAULT "?" NOT NULL,
    "min_vein02" TEXT DEFAULT "?" NOT NULL,
    "min_vein03" TEXT DEFAULT "?" NOT NULL,
    "min_vein04" TEXT DEFAULT "?" NOT NULL,
    "deformation_episode" TEXT DEFAULT "?" NOT NULL,
    "is_boundary" TEXT DEFAULT "Y",
    "is_surface" TEXT DEFAULT "Y",
	"mapped_scale"  TEXT,    
    "comments" TEXT,
    "status" TEXT DEFAULT "C" NOT NULL,
    "user_entered" TEXT NOT NULL,
    "date_entered" DATETIME NOT NULL,
    "user_updated" TEXT,
    "date_updated" DATETIME,
    FOREIGN KEY("line_type_code") REFERENCES "dic_line_type_bedrock"("line_type"),
    FOREIGN KEY("geol_theme") REFERENCES "dic_geol_theme_cat"("theme"),
    FOREIGN KEY("geol_theme_category") REFERENCES "dic_geol_theme_cat"("category"), 
    FOREIGN KEY("hang_wall_dir") REFERENCES "dic_compass"("abbrv"),
    FOREIGN KEY("young_dir") REFERENCES "dic_compass"("abbrv"),
    FOREIGN KEY("mineral") REFERENCES "bdic_mineral"("code"),
    FOREIGN KEY("min_vein_01") REFERENCES "dic_mineral"("code"),
    FOREIGN KEY("min_vein_02") REFERENCES "dic_mineral"("code"),  
    FOREIGN KEY("min_vein_03") REFERENCES "dic_mineral"("code"),
    FOREIGN KEY("min_vein_04") REFERENCES "dic_min_vein"("code"),
    FOREIGN KEY("deformation_episode") REFERENCES "dic_deformation_episode"("abbrev"),
    PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "superficial_line" (
    "fid" INTEGER NOT NULL,
    "objectid" INTEGER UNIQUE,
    "uuid" TEXT NOT NULL UNIQUE,
    "geol_theme" TEXT NOT NULL,
    "geol_theme_category" TEXT NOT NULL,
    "line_type" TEXT NOT NULL,
    "asymmetry_linear" TEXT DEFAULT "?" NOT NULL,
    "asymmetry_perpen" TEXT DEFAULT "?" NOT NULL,
    "is_boundary_yn" TEXT DEFAULT "Y", 
	"mapped_scale"  TEXT,
    "comments" TEXT,
    "status" TEXT DEFAULT "C" NOT NULL,
    "user_entered" TEXT NOT NULL,
    "date_entered" DATETIME NOT NULL,
    "user_updated" TEXT,
    "date_updated" DATETIME,
    FOREIGN KEY("line_type_code") REFERENCES "dic_line_type_superficial"("line_type"),
    FOREIGN KEY("geol_theme") REFERENCES "dic_geol_theme_cat"("theme"),
    FOREIGN KEY("geol_theme_category") REFERENCES "dic_geol_theme_cat"("category"), 
    FOREIGN KEY("asymmetry_linear") REFERENCES "dic_compass"("abbrv"),
    FOREIGN KEY("asymmetry_perpen") REFERENCES "dic_compass"("abbrv"),
    PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "terrain_line" (
    "fid" INTEGER NOT NULL,
    "objectid" INTEGER UNIQUE,
    "uuid" TEXT NOT NULL UNIQUE,
    "geol_theme" TEXT NOT NULL,
    "geol_theme_category" TEXT NOT NULL,
    "line_type" TEXT NOT NULL,
    "asymmetry_linear" TEXT DEFAULT "?" NOT NULL,
    "asymmetry_perpen" TEXT DEFAULT "?" NOT NULL,
    "is_boundary_yn" TEXT, 
    "mapped_scale"  TEXT,
    "comments" TEXT,
    "status" TEXT DEFAULT "C" NOT NULL,
    "user_entered" TEXT NOT NULL,
    "date_entered" DATETIME NOT NULL,
    "user_updated" TEXT,
    "date_updated" DATETIME,
    FOREIGN KEY("line_type_code") REFERENCES "dic_line_type_terrain"("line_type"),
    FOREIGN KEY("geol_theme") REFERENCES "dic_geol_theme_cat"("theme"),
    FOREIGN KEY("geol_theme_category") REFERENCES "dic_geol_theme_cat"("category"), 
    FOREIGN KEY("asymmetry_linear") REFERENCES "dic_compass"("abbrv"),
    FOREIGN KEY("asymmetry_perpen") REFERENCES "dic_compass"("abbrv"),
    PRIMARY KEY("fid" AUTOINCREMENT)
)
CREATE TABLE "mass_move_line" (
    "fid" INTEGER NOT NULL,
    "objectid" INTEGER UNIQUE,
    "uuid" TEXT NOT NULL UNIQUE,
    "geol_theme" TEXT NOT NULL,
    "geol_theme_category" TEXT NOT NULL,
    "line_type" TEXT NOT NULL,
    "asymmetry_linear" TEXT DEFAULT "?" NOT NULL,
    "asymmetry_perpen" TEXT DEFAULT "?" NOT NULL,
    "is_boundary_yn" TEXT,  
	"mapped_scale"  TEXT,
    "comments" TEXT,
    "status" TEXT NOT NULL DEFAULT "C",
    "user_entered" TEXT NOT NULL,
    "date_entered" DATETIME NOT NULL,
    "user_updated" TEXT,
    "date_updated" DATETIME,
    FOREIGN KEY("line_type_code") REFERENCES "dic_line_type_mass_move"("line_type"),
    FOREIGN KEY("geol_theme") REFERENCES "dic_geol_theme_cat"("theme"),
    FOREIGN KEY("geol_theme_category") REFERENCES "dic_geol_theme_cat"("category"), 
    FOREIGN KEY("asymmetry_linear") REFERENCES "dic_compass"("abbrv"),
    FOREIGN KEY("asymmetry_perpen") REFERENCES "dic_compass"("abbrv"),
    PRIMARY KEY("fid" AUTOINCREMENT)
)