# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldDataCapture
                                 A QGIS plugin
 This plugin aids with field data capture based work
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-28
        copyright            : (C) 2023 by BGS Informatics
        email                : enquiries@bgs.ac.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FieldDataCapture class from file FieldDataCapture.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .field_data_capture import FieldDataCapture
    return FieldDataCapture(iface)
