# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldDataCapture
                                 A QGIS plugin
 This plugin aids with field data capture based work
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2023 by BGS Informatics
        email                : enquiries@bgs.ac.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import sqlite3
from pathlib import Path
from typing import Optional

from qgis.core import (
    QgsDataProvider,
    QgsProject,
    QgsVectorLayer,
)
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMessageBox,
)

# Initialize Qt resources from file resources.py
from .resources import *

from .config import (
    ATTRIBUTE_TABLES,
    DICTIONARIES,
    FEATURE_TABLES,
    VIEWS,
    TABLE_LIST,
)
from .create_gpkg_from_sql import main as gpkg_from_sql
from .create_gpkg_from_sql import (
    add_test_data,
    WORKDIR,
)
from .utils import ipdb_breakpoint


class FieldDataCapture:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        # locale = QSettings().value('locale/userLocale')[0:2]
        # locale_path = os.path.join(
        #     self.plugin_dir,
        #     'i18n',
        #     'FieldDataCapture_{}.qm'.format(locale))

        # if os.path.exists(locale_path):
        #     self.translator = QTranslator()
        #     self.translator.load(locale_path)
        #     QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Field Data Capture')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.gpkg_filename = Path("field-data-capture.gpkg")


    @property
    def project_dir(self) -> Path:
        """
        Get the current project directory.
        """
        return Path(QgsProject.instance().readPath("./"))


    @property
    def db_file(self) -> Path:
        """
        Get the db file path from the current project.
        """
        return self.project_dir / self.gpkg_filename


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FieldDataCapture', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/field_data_capture/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Add GeoPackage to Project'),
            callback=self.add_gpkg_to_project,
            parent=self.iface.mainWindow(),
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Add GeoPackage Layers to Project'),
            callback=self.add_gpkg_layers_to_project,
            parent=self.iface.mainWindow(),
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Add Test Data to Project'),
            callback=self.add_test_data_to_project,
            parent=self.iface.mainWindow(),
        )

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Field Data Capture'),
                action)
            self.iface.removeToolBarIcon(action)


    @staticmethod
    def project_is_active() -> bool:
        if QgsProject.instance().fileName() != '':
            return True
        else:
            QMessageBox.information(None, "Information", "Please open a saved project.")
            return False


    def add_gpkg_to_project(self) -> None:
        """
        Add the GeoPackage file to the current project.
        """
        # Check that we have an open project
        if not self.project_is_active():
            return None

        run = True
        if self.db_file.exists():
            result = QMessageBox.question(
                None, "File Already Exists",
                f"The file already exists, would you like to overwrite the file?\n\n{self.db_file}",
            )
            if result == QMessageBox.No:
                run = False

        if run:
            QMessageBox.information(None, "Information", f"Created GeoPackage:\n\n{self.db_file}")
            gpkg_from_sql(db_file=self.db_file)


    def add_gpkg_layers_to_project(self) -> None:
        """
        Add the GeoPackage layers to the current project.
        """
        # Check that we have an open project and a geopackage
        if not self.project_is_active():
            return None
        if not self.db_file.exists():
            QMessageBox.information(None, "Information", f"Could not find file:\n\n{self.db_file}")
            return None

        groups_layers = self.get_groups_layers()

        # Get layers root
        root = QgsProject.instance().layerTreeRoot()
        # Get db layers
        db_root_layer = QgsVectorLayer(str(self.db_file), "", "ogr")
        db_layers = db_root_layer.dataProvider().subLayers()
        db_layer_names = [
            layer.split(QgsDataProvider.SUBLAYER_SEPARATOR)[1]
            for layer in db_layers
        ]

        vector_layers = []
        for group_name, group_layer_names in groups_layers.items():
            # Create the group if required
            add_to_legend = True
            if group_name is not None:
                group = root.addGroup(group_name)
                add_to_legend = False

            for layer_name in group_layer_names:
                # If the layer name in the dictionary is in the list of layers in the db file
                if layer_name in db_layer_names:

                    # Create layer
                    uri = f"{self.db_file}|layername={layer_name}"
                    vector_layer = QgsVectorLayer(uri, layer_name, "ogr")
                    QgsProject.instance().addMapLayer(vector_layer, add_to_legend)
                    vector_layers.append(vector_layer)

                    # Add layer to a group if required
                    if group_name is not None:
                        group.addLayer(vector_layer)

        # We apply relationships and then styles after all layers are added to avoid conflicts
        self.find_create_relationships(vector_layers)
        self.apply_qml_styles(vector_layers)


    def get_groups_layers(self) -> dict[Optional[str], list[str]]:
        """
        Get a dictionary of tables/layers which will represent the QGIS layer tree.
        """
        # Create inital structure
        groups_layers = {
            None: FEATURE_TABLES,
            "views": VIEWS,
            "locality_data": ATTRIBUTE_TABLES,
            "metadata": DICTIONARIES,
        }

        # Sort the lists
        for layer_name, table_set in groups_layers.items():
            table_list = list(table_set)
            table_list.sort()
            groups_layers[layer_name] = table_list

        # Move the project layer
        project_name = "project"
        groups_layers["locality_data"].remove(project_name)
        groups_layers["metadata"].insert(0, project_name)

        return groups_layers


    def apply_qml_styles(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Find and apply the QML style files for the given layers.
        """
        plugin_styles_dir = WORKDIR / "styles"
        vector_layer_names = {
            vector_layer.name(): vector_layer
            for vector_layer in vector_layers
        }

        # Create the directory to store style files in the current project
        styles_dir = self.project_dir / "styles"
        styles_dir.mkdir(parents=True, exist_ok=True)

        for plugin_qml_file in plugin_styles_dir.glob("*.qml"):
            # If a matching vector layer exists for the qml file
            if plugin_qml_file.stem in vector_layer_names:
                # Copy the plugin qml file to the new project qml file
                new_qml_file = styles_dir / plugin_qml_file.name
                new_qml_file.write_bytes(plugin_qml_file.read_bytes())

                # Apply the new style
                vector_layer_names[new_qml_file.stem].loadNamedStyle(str(new_qml_file))
                vector_layer_names[new_qml_file.stem].triggerRepaint()


    def find_create_relationships(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Automatically find and create relationships between vector layers.
        """
        relation_manager = QgsProject.instance().relationManager()
        relations = relation_manager.discoverRelations([], vector_layers)
        for relation in relations:
            relation_manager.addRelation(relation)


    def add_test_data_to_project(self) -> None:
        """
        Add the test data set to the current project.
        """
        # Check that we have an open project and a geopackage
        if not self.project_is_active():
            return None
        if not self.db_file.exists():
            QMessageBox.information(None, "Information", f"Could not find file:\n\n{self.db_file}")
            return None

        with sqlite3.connect(self.db_file) as conn:
            conn.enable_load_extension(True)
            add_test_data(conn)
            self.repaint_fdc_layers()
            QMessageBox.information(None, "Information", f"Added test data set to:\n\n{self.db_file}")


    def repaint_fdc_layers(self) -> None:
        """
        Trigger a repaint for only the layers which come from the Field Data Capture plugin.
        """
        for layer in QgsProject.instance().mapLayers().values():
            if layer.name() in set(TABLE_LIST):
                layer.triggerRepaint()
