# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldDataCapture
                                 A QGIS plugin
 This plugin aids with field data capture based work
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2023 by BGS Informatics
        email                : enquiries@bgs.ac.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import logging
import os.path
import pprint
import sqlite3
from collections import defaultdict
from pathlib import Path
from typing import (
    Any,
    Callable,
    Optional,
)
from xml.dom import minidom
from xml.etree.ElementTree import canonicalize

from qgis.core import (
    Qgis,
    QgsEditorWidgetSetup,
    QgsLayerTree,
    QgsLayerTreeGroup,
    QgsMapLayer,
    QgsMapLayerDependency,
    QgsProject,
    QgsRuleBasedRenderer,
    QgsSymbol,
    QgsVectorLayer,
)
from qgis.gui import (
    QgisInterface,
    QgsMapTool,
)
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import (
    QColor,
    QIcon,
)
from qgis.PyQt.QtWidgets import (
    QAction,
    QMenu,
    QMessageBox,
    QToolBar,
    QWidget,
)

# Initialize Qt resources from file resources.py
from .resources import *  # noqa

from .config import (
    FEATURE_TABLES_LINES,
    LOCALITY_POINT_CHILDREN,
    TABLE_LIST,
    LAYER_TREE_STRUCTURE,
)
from .create_gpkg_from_sql import main as gpkg_from_sql
from .create_gpkg_from_sql import (
    add_test_data,
    WORKDIR,
)
from .line_layer_selector import LineLayerSelector
from .file_linker import FileLinker
from .project_validation import (
    ValidationStatus,
    validate_project,
)
from .report_builder import ReportBuilder
from .quick_map_tools import (
    QuickAddTool,
    QuickEditTool,
    QuickDeleteTool,
)
from .utils import (  # noqa
    FieldDataCaptureProject,
    ipdb_breakpoint,
)

logger = logging.getLogger('fdc')
logging.basicConfig(level=logging.DEBUG)


class FieldDataCapture(FieldDataCaptureProject):
    """QGIS Plugin Implementation."""

    def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface: QgisInterface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        # locale = QSettings().value('locale/userLocale')[0:2]
        # locale_path = os.path.join(
        #     self.plugin_dir,
        #     'i18n',
        #     'FieldDataCapture_{}.qm'.format(locale))

        # if os.path.exists(locale_path):
        #     self.translator = QTranslator()
        #     self.translator.load(locale_path)
        #     QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Field Data Capture')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.toolbar: QToolBar
        self.quick_map_tool_buttons: dict[str, QAction] = {}
        self.quick_map_tool: Optional[QgsMapTool] = None
        self.file_linker: Optional[FileLinker] = None
        self.line_layer_selector: Optional[LineLayerSelector] = None
        self.last_quick_add_line_type: Optional[dict[str, str]] = None

        logger.debug("Field Data Capture plugin initialised.")


    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        noinspection PyMethodMayBeStatic

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FieldDataCapture', message)


    def add_action(
        self,
        icon_path: Optional[str],
        text: str,
        callback: Callable,
        enabled_flag: bool = True,
        add_to_menu: bool = True,
        add_to_toolbar: bool = False,
        status_tip: Optional[str] = None,
        whats_this: Optional[str] = None,
        parent: Optional[QWidget] = None,
        submenu: Optional[QMenu] = None,
        checkable: bool = False,
    ) -> QAction:
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to False.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param submenu: Optional QMenu widget. The new action will be added
            to this submenu.
        :type submenu: QMenu

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.setEnabled(enabled_flag)

        if callback is not None:
            action.triggered.connect(callback)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Field Data Capture toolbar
            self.toolbar.addAction(action)

        if add_to_menu and submenu is None:
            self.iface.addPluginToMenu(
                self.menu,
                action,
            )

        if submenu is not None:
            submenu.addAction(action)

        if checkable:
            action.setCheckable(True)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Create a new toolbar for the plugin
        toolbar_text = "Field Data Capture Toolbar"
        self.toolbar = self.iface.addToolBar(toolbar_text)
        self.toolbar.setToolTip(toolbar_text)
        self.toolbar.setObjectName("".join(toolbar_text))

        self.quick_map_tool_buttons["fdc_locality_point_add"] = self.add_action(
            str(self.icons_dir / "quick_locality_add.png"),
            text=self.tr(u'Quick Add Locality Point'),
            callback=lambda: self.toggle_quick_map_tool(layer_name="locality_point", mode="add"),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.quick_map_tool_buttons["fdc_locality_point_edit"] = self.add_action(
            str(self.icons_dir / "quick_locality_edit.png"),
            text=self.tr(u'Quick Edit Locality Point'),
            callback=lambda: self.toggle_quick_map_tool(layer_name="locality_point", mode="edit"),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.quick_map_tool_buttons["fdc_locality_point_delete"] = self.add_action(
            str(self.icons_dir / "quick_locality_delete.png"),
            text=self.tr(u'Quick Delete Locality Point'),
            callback=lambda: self.toggle_quick_map_tool(layer_name="locality_point", mode="delete"),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        # Create a single add/edit/delete button for all line tables
        self.quick_map_tool_buttons["fdc_lines_add"] = self.add_action(
            str(self.icons_dir / "quick_lines_add.png"),
            text=self.tr(u'Quick Add Line'),
            callback=self.select_quick_line_layer_add,
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.quick_map_tool_buttons["fdc_lines_edit"] = self.add_action(
            str(self.icons_dir / "quick_lines_edit.png"),
            text=self.tr(u'Quick Edit Line'),
            callback=lambda: self.toggle_quick_map_tool(
                layer_name=FEATURE_TABLES_LINES,
                mode="edit",
                layers_ref="lines",
            ),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.quick_map_tool_buttons["fdc_lines_delete"] = self.add_action(
            str(self.icons_dir / "quick_lines_delete.png"),
            text=self.tr(u'Quick Delete Line'),
            callback=lambda: self.toggle_quick_map_tool(
                layer_name=FEATURE_TABLES_LINES,
                mode="delete",
                layers_ref="lines",
            ),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        # Link all line tables to the same add button
        for line_table in FEATURE_TABLES_LINES:
            self.quick_map_tool_buttons[f"fdc_{line_table}_add"] = self.quick_map_tool_buttons["fdc_lines_add"]

        self.add_action(
            str(self.icons_dir / "open_project_folder.png"),
            text=self.tr(u'Open Project Folder'),
            callback=lambda: self.open_local_filepath(self.project_dir),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
        )

        self.add_action(
            None,
            text=self.tr(u'Link Photos and Media'),
            callback=self.open_file_linker,
            parent=self.iface.mainWindow(),
        )

        self.add_action(
            None,
            text=self.tr(u'Create Field Report'),
            callback=self.create_field_report,
            parent=self.iface.mainWindow(),
        )

        self.add_action(
            None,
            text=self.tr(u'Validate Current Project'),
            callback=self.run_project_validation,
            parent=self.iface.mainWindow(),
        )

        # Setup advanced tools menu
        # We still create a QAction, but we set its menu with a new QMenu
        advanced_submenu_action = self.add_action(
            None,
            text=self.tr(u'More...'),
            callback=None,
            parent=self.iface.mainWindow(),
        )
        advanced_submenu = QMenu()
        advanced_submenu_action.setMenu(advanced_submenu)

        self.button_setup_project = self.add_action(
            None,
            text=self.tr(u'Setup Project'),
            callback=lambda: self.run_function_list(functions=[
                self.add_gpkg_to_project,
                self.add_gpkg_layers_to_project,
                self.open_create_field_project,
            ]),
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu
        )

        self.add_action(
            None,
            text=self.tr(u'Add Field Project'),
            callback=self.open_create_field_project,
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu
        )

        advanced_submenu.addSeparator()

        self.add_action(
            None,
            text=self.tr(u'Setup Test Project'),
            callback=lambda: self.run_function_list(functions=[
                self.add_gpkg_to_project,
                self.add_gpkg_layers_to_project,
                self.add_test_data_to_project,
            ]),
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu,
        )

        self.add_action(
            None,
            text=self.tr(u'Export Styles to QML'),
            callback=self.export_qml_styles,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu,
        )

        advanced_submenu.addSeparator()

        self.add_action(
            None,
            text=self.tr(u'Add GeoPackage to Project'),
            callback=self.add_gpkg_to_project,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu,
        )

        self.add_action(
            None,
            text=self.tr(u'Add GeoPackage Layers to Project'),
            callback=self.add_gpkg_layers_to_project,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu,
        )

        self.add_action(
            None,
            text=self.tr(u'Add Test Data to Project'),
            callback=self.add_test_data_to_project,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=advanced_submenu,
        )

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Disable the current QuickMapTool if there is one
        self.disable_current_quick_map_tool()
        self.close_file_linker()

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Field Data Capture'),
                action)
            self.iface.removeToolBarIcon(action)

        # Delete the Field Data Capture toolbar
        del self.toolbar


    def run_function_list(self, functions: list[Callable]) -> bool:
        """
        Run all the given functions in order.
        Each function must return a boolean indicating it's success.
        If a function returns False, function execution will end.
        Returns a boolean indicating success of the process.
        """
        for function_ in functions:
            return_ = function_()
            # We don't want to continue through the setup if a process fails
            if return_ is False:
                return False

        return True


    def add_gpkg_to_project(self) -> bool:
        """
        Add the GeoPackage file to the current project.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True):
            return False

        if self.db_file.exists():
            result = QMessageBox.question(
                None, "File Already Exists",
                f"The file already exists, would you like to overwrite the file?\n\n{self.db_file}",
            )
            if result == QMessageBox.No:
                return False

        gpkg_from_sql(db_file=self.db_file)
        QMessageBox.information(None, "Information", f"Created GeoPackage:\n\n{self.db_file}")
        return True


    def add_gpkg_layers_to_project(self) -> bool:
        """
        Add the GeoPackage layers to the current project.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True):
            return False

        # Get layer tree root
        root = QgsProject.instance().layerTreeRoot()

        vector_layers = []
        for idx, item in enumerate(LAYER_TREE_STRUCTURE):

            # Create the group if required
            group = None
            add_to_legend = True
            if item["group"] is not None:
                group = self.create_legend_group(root, item["group"], idx)
                add_to_legend = False

            for layer_name in item["tables"]:
                # Create layer
                uri = f"{self.db_file}|layername={layer_name}"
                vector_layer = QgsVectorLayer(uri, layer_name, "ogr")

                # Here, we purposefully insert a layer manually rather than relying on addMapLayer
                # This is because addMapLayer adds the given layer to the top of the layer tree view,
                # but we want to add each layer to a specific index
                if add_to_legend:
                    root.insertLayer(idx, vector_layer)
                else:
                    tree_layer = group.addLayer(vector_layer)
                    # Collapse all layers added to a group
                    tree_layer.setExpanded(False)

                QgsProject.instance().addMapLayer(vector_layer, addToLegend=False)
                vector_layers.append(vector_layer)

        # Changes to layers are only done after all layers are added to avoid issues
        # Create relationships first to ensure their corresponding styles/properties can be set
        self.find_create_relationships(vector_layers)
        self.apply_qml_styles(vector_layers)
        self.set_vector_layer_properties(vector_layers)
        # self.set_view_lithology_rules()

        # Create empty user directories
        for directory in [self.photos_dir, self.media_dir]:
            directory.mkdir(parents=True, exist_ok=True)
            (directory / self.placeholder_filename).touch()

        for layer in vector_layers:
            self.refresh_relation_reference_widgets(layer)

        QMessageBox.information(
            None, "Information",
            "GeoPackage layers loaded.\n\nNow set field project boundary polygon and metadata.",
        )
        return True


    def create_legend_group(
        self,
        root: QgsLayerTree,
        group_name: str,
        idx: int,
    ) -> QgsLayerTreeGroup:
        """
        Create a group with the given name.
        Returns the new group.
        """
        # Insert a group into the layer tree at the given index
        group = root.insertGroup(idx, group_name)
        # If it is the lines group, expand it
        if group_name == "lines":
            group.setExpanded(True)
        else:
            group.setExpanded(False)
        return group


    def set_vector_layer_properties(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Set the properties for the given vector layers.
        This includes setting layer dependencies, read only properties, and display expressions.
        """
        for vector_layer in vector_layers:

            # Set display expressions for certain layers
            display_expressions = {
                "lithology": """
                    attribute(
                        get_feature(
                            'dic_rock_field',
                            'code',
                            "lithology_code"
                        ),
                        'label'
                    ) + ' (' + "lithology_code" + ')'
                """,
                "manmade_landform": """
                    attribute(
                        get_feature(
                            'dic_manmade_landform',
                            'code',
                            "manmade_type_code"
                        ),
                        'description'
                    )
                """,
                "media": '''"media_link" + ' | ' + "media_description"''',
                "photo": '''"photo_file" + ' | ' + "caption"''',
                "sample": '''"sample_id"''',
                "structural_measurement": """
                    attribute(
                        get_feature(
                            'dic_structure',
                            'code',
                            "structure_type_code"
                        ),
                        'description'
                    )
                """,
                "superficial_landform": """
                    attribute(
                        get_feature(
                            'dic_superficial_landform',
                            'code',
                            "superficial_type_code"
                        ),
                        'description'
                    )
                """,
                "dic_rock_field": """"label" + ' (' + "code" + ')'""",
                "_lnk_rock_project": """
                    attribute(
                        get_feature(
                            'field_project',
                            'uuid',
                            "field_project_uuid"),
                        'short_name')

                    + ' - ' +

                    attribute(
                        get_feature(
                            'dic_rock_field',
                            'code',
                            "rock_code"),
                        'label')

                    + ' - ' +

                    "rock_code"
                """,
            }
            if vector_layer.name() in display_expressions:
                vector_layer.setDisplayExpression(display_expressions[vector_layer.name()])

            # Set layer dependencies for views
            layer_dependencies = {
                "view_lithology": "lithology",
                "view_manmade_landform": "manmade_landform",
                "view_media": "media",
                "view_photo": "photo",
                "view_structural_measurement": "structural_measurement",
                "view_sample": "sample",
                "view_superficial_landform": "superficial_landform",
            }
            if vector_layer.name() in layer_dependencies:
                dependent_layer = QgsProject.instance().mapLayersByName(layer_dependencies[vector_layer.name()])[0]
                dependency = QgsMapLayerDependency(layerId=dependent_layer.id())
                vector_layer.setDependencies([dependency])

            # Set dictionary layers to read only
            if vector_layer.name().startswith("dic"):
                vector_layer.setReadOnly()

            # Set default flags for field_project layer other than Identifiable
            if vector_layer.name() == "field_project":
                vector_layer.setFlags(QgsMapLayer.LayerFlag.Searchable | QgsMapLayer.LayerFlag.Removable)

            # Hide certain layers
            hide_layers = {
                "view_media",
                "view_photo",
                "view_sample",
            }
            if vector_layer.name() in hide_layers:
                QgsProject.instance().layerTreeRoot().findLayer(vector_layer).setItemVisibilityChecked(False)


    def refresh_relation_reference_widgets(self, layer: QgsVectorLayer) -> None:
        """
        Recreate the relation reference widgets ensuring that they use the
        layer id that corresponds to the current project relationships.
        """
        relation_manager = QgsProject.instance().relationManager()
        widgets = self.editor_widget_metadata(layer)

        for idx, field_name in enumerate(widgets):
            if widgets[field_name]["type"] == "RelationReference":
                logger.debug("Updating relation widget for %s.%s",
                             layer.name(), field_name)
                config = widgets[field_name]["config"]

                matching_relations = relation_manager.relationsByName(config['Relation'])
                if len(matching_relations) != 1:
                    msg = f"Relation name ({config['Relation']}) is not unique"
                    raise ValueError(msg)
                relation = matching_relations[0]

                config.update({'ReferencedLayerId': relation.referencedLayerId()})
                new_widget = QgsEditorWidgetSetup('RelationReference', config)
                layer.setEditorWidgetSetup(idx, new_widget)

    @staticmethod
    def editor_widget_metadata(layer: QgsVectorLayer) -> dict[str, dict[str, Any]]:
        widgets = {}

        for field in layer.fields():
            widget_setup = field.editorWidgetSetup()
            widgets[field.name()] = {
                'type': widget_setup.type(),
                'config': widget_setup.config()
            }

        return widgets

    def log_active_layer_widgets(self) -> None:
        layer = self.iface.activeLayer()
        logger.debug("Layer ID: %s", layer.id())

        for field in layer.fields():
            widget_setup = field.editorWidgetSetup()
            if widget_setup.isNull():
                logger.debug("No editor widget for field '%s'", field.name())
            else:
                widget = {
                    'field': field.name(),
                    'widget_type': widget_setup.type(),
                    'widget_config': widget_setup.config()
                }
                logger.debug('\n' + pprint.pformat(widget, indent=2, sort_dicts=False))

            if widget_setup.type() == "RelationReference":
                relation_manager = QgsProject.instance().relationManager()
                # Check for duplicate relations
                matching_relations = relation_manager.relationsByName(widget_setup.config()['Relation'])
                logger.debug('Matching relations: %s', matching_relations)

                try:
                    relation = matching_relations[0]
                    relation_metadata = {
                        'name': relation.name(),
                        'isValid': relation.isValid(),
                        'referencingLayer': relation.referencingLayer(),
                        'referencingLayerId': relation.referencingLayerId(),
                        'referencedLayer': relation.referencedLayer(),
                        'referencedLayerId': relation.referencedLayerId(),
                    }
                    msg = pprint.pformat(relation_metadata, indent=2, sort_dicts=False)
                    logger.debug('Relation metadata:\n%s', msg)
                except IndexError:
                    logger.debug('No relations defined in project')


    def apply_qml_styles(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Find and apply the QML style files for the given layers.
        """
        vector_layer_names = {
            vector_layer.name(): vector_layer
            for vector_layer in vector_layers
        }
        self.copy_plugin_files_to_project(plugin_src="styles", project_dest="styles")

        for qml_file in self.styles_dir.glob("*"):
            if qml_file.stem in vector_layer_names:
                # Apply the new style
                vector_layer_names[qml_file.stem].loadNamedStyle(str(qml_file))
                vector_layer_names[qml_file.stem].triggerRepaint()


    def find_create_relationships(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Automatically find and create relationships between vector layers.
        """
        relation_manager = QgsProject.instance().relationManager()
        relations = relation_manager.discoverRelations([], vector_layers)
        for relation in relations:
            # Using the referencingLayer (child) creates other composition relations that are
            # unnecessary here, so the referencedLayer (parent) needs to be checked
            if relation.referencedLayer().name() == 'locality_point':
                # For QGIS relations, 0 = association (default), 1 = composition
                relation.setStrength(Qgis.RelationshipStrength(1))
            relation_manager.addRelation(relation)


    def set_view_lithology_rules(self) -> None:
        """
        Set the rules for the renderer so that the hex colours are used.
        See this stackexchange post for solution details:
        https://gis.stackexchange.com/questions/435463/rule-based-renderer-in-pyqgis?noredirect=1&lq=1
        """
        view_lithology_layer = QgsProject.instance().mapLayersByName("view_lithology")[0]

        symbol = QgsSymbol.defaultSymbol(view_lithology_layer.geometryType())
        renderer = QgsRuleBasedRenderer(symbol)
        root_rule = renderer.rootRule()

        simple_lithology_categories, simple_lithology_colours = self.get_lithology_categories_and_colours()

        for category, simple_lithology_list in simple_lithology_categories.items():
            hex_colour = simple_lithology_colours[category]

            expression = f"simple_lithology IN ({simple_lithology_list})"

            # Create the rule
            rule = root_rule.children()[0].clone()
            rule.setLabel(category)
            rule.setFilterExpression(expression)
            rule.symbol().setColor(QColor(hex_colour))
            rule.symbol().setSize(5)

            # Add the rule to the list of rules
            root_rule.appendChild(rule)

        # Delete the default rule
        root_rule.removeChildAt(0)
        view_lithology_layer.setRenderer(renderer)
        view_lithology_layer.triggerRepaint()


    def get_lithology_categories_and_colours(self) -> tuple[dict[str, str], dict[str, str]]:
        """
        Generate the lithology categories and colours from the _simple_lithology_categories table
        and the _simple_lithology table.
        The values in the categories dictionary are the list of simple lithologies in a comma separated string.
        """
        with sqlite3.connect(self.db_file) as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                    SELECT
                        slc.simple_lithology_category,
                        slc.simple_lithology,
                        sl.hex_colour
                    FROM
                        _simple_lithology_categories AS slc
                    LEFT JOIN
                        _simple_lithology AS sl ON slc.simple_lithology = sl.name
                    """
            )
            rows = cursor.fetchall()
        conn.close()

        simple_lithology_categories = defaultdict(list)
        simple_lithology_colours = {}
        for category, lithology, hex_colour in rows:
            simple_lithology_categories[category].append(lithology)
            simple_lithology_colours[category] = hex_colour

        for category, lithology_list in simple_lithology_categories.items():
            str_list = ",".join(f"'{lithology}'" for lithology in lithology_list)
            simple_lithology_categories[category] = str_list

        return simple_lithology_categories, simple_lithology_colours


    def open_create_field_project(self) -> bool:
        """
        Enable the QuickMapTool for adding a new field_project.
        The tool will automatically deactivate after a new feature is saved to the layer.
        Returns a boolean indicating success of the process.
        """
        layer_name = "field_project"
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, layer_name_exists=layer_name) or not self.toggle_quick_map_tool(layer_name, mode="add"):  # noqa
            return False
        return True


    def create_field_report(self) -> bool:
        """
        Create and save a field report.
        If an older report already exists, issue a warning with an option to cancel.
        If confirmed, parse the locality point layer creating an entry for each point
        in an HTML document using a Jinja2 template, overwriting the older report if necessary.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True, field_project_exists=True):  # noqa
            return False

        ReportBuilder().create_field_report()


    def add_test_data_to_project(self) -> bool:
        """
        Add the test data set to the current project.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True):
            return False

        with sqlite3.connect(self.db_file) as conn:
            conn.enable_load_extension(True)
            add_test_data(conn)
        conn.close()

        # Copy test data media files across into current project
        self.copy_plugin_files_to_project(plugin_src="test/data/photos", project_dest="photos")
        self.copy_plugin_files_to_project(plugin_src="test/data/media", project_dest="media")
        self.iface.mapCanvas().refresh()
        QMessageBox.information(None, "Information", f"Added test data set to:\n\n{self.db_file}")
        return True


    def copy_plugin_files_to_project(self, plugin_src: Path, project_dest: Path) -> None:
        """
        Copy the files from the given plugin source directory into the given project destination directory.
        """
        plugin_src_dir = WORKDIR / plugin_src
        project_dest_dir = self.project_dir / project_dest
        project_dest_dir.mkdir(parents=True, exist_ok=True)

        for src_file in plugin_src_dir.glob("*"):
            dest_file = project_dest_dir / src_file.name
            dest_file.write_bytes(src_file.read_bytes())


    def export_qml_styles(self) -> bool:
        """
        Export the QML styles for layers which belong to the Field Data Capture project.
        These are saved into the current project's styles directory.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True):
            return False

        # Compare the QGIS version in the existing styles to the current QGIS version
        # Get the first existing QML style and parse it's XML
        existing_xml_style = minidom.parse(str(list(self.styles_dir.glob("*.qml"))[0]))
        existing_version = existing_xml_style.getElementsByTagName("qgis")[0].attributes["version"].value
        current_version = Qgis.version()
        if existing_version != current_version:
            result = QMessageBox.question(
                None, "Conflicting QGIS Versions",
                (
                    f"The existing QML files are from QGIS '{existing_version}', "
                    f"but you are using QGIS '{current_version}'. "
                    "Continuing will cause bad style diffs.\n\nDo you want to continue?"
                ),
            )
            if result == QMessageBox.No:
                return False

        # Export the current styles
        exported_styles = 0
        for table_name in TABLE_LIST:
            layer_style_path = self.styles_dir / (table_name + ".qml")
            # If the layer exists and a style file has already been saved for it
            if self.check_layer_exists(table_name) and layer_style_path.exists():
                exported_styles += 1

                # Save the style of the current layer
                layer = QgsProject.instance().mapLayersByName(table_name)[0]
                layer.saveNamedStyle(
                    str(layer_style_path),
                    categories=QgsMapLayer.Symbology | QgsMapLayer.Labeling | QgsMapLayer.Fields | QgsMapLayer.Forms | QgsMapLayer.MapTips,  # noqa
                )

                # Read the newly created XML file
                raw_xml = layer_style_path.read_text()
                # Canonicalize the XML data and save back to the same file
                # Set the newline manually to force LF line endings
                with open(layer_style_path, "w", newline="\n") as qml_file:
                    canonicalize(xml_data=raw_xml, out=qml_file)

        QMessageBox.information(
            None, "Information",
            f"{exported_styles} Field Data Capture styles have been exported to:\n\n{self.styles_dir}",
        )
        return True


    def select_quick_line_layer_add(self) -> bool:
        """
        Get the user to select a line layer to be used with a QuickMapTool with the add mode.
        Returns a boolean indicating if the given tool was toggled.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True, field_project_exists=True) or self.warn_unsaved_locality_data():  # noqa
            # Disable active tool if there is one and untoggle buttons to ensure things are not left in a bad state
            self.disable_current_quick_map_tool()
            self.untoggle_quick_map_tool_buttons()
            return False

        # Ensure the button is toggled, it can be untoggled if pressed again to select a different line type
        self.quick_map_tool_buttons["fdc_lines_add"].setChecked(True)

        # Open line layer selector tool
        self.line_layer_selector = LineLayerSelector(self.last_quick_add_line_type)
        self.line_layer_selector.line_layer_selector_confirm.connect(self.confirm_line_layer_selector)
        self.line_layer_selector.line_layer_selector_closed.connect(self.close_line_layer_selector)
        # Show it in a modal state
        self.line_layer_selector.exec()
        return True


    def confirm_line_layer_selector(self, line_layer: str, line_type: str) -> None:
        """
        Confirm the selection from the line layer selector and toggling the required tool.
        """
        # Save selection
        self.last_quick_add_line_type = {
            "layer": line_layer,
            "type": line_type,
        }

        self.close_line_layer_selector(reset_buttons=False)
        self.toggle_quick_map_tool(
            layer_name=line_layer,
            mode="add",
            prepopulate={"line_type_code": line_type},
        )


    def close_line_layer_selector(self, reset_buttons: bool = True) -> None:
        """
        Delete the current line layer selector object if there is one.
        """
        if reset_buttons:
            self.disable_current_quick_map_tool()
            self.untoggle_quick_map_tool_buttons()
        if self.line_layer_selector is not None:
            # Make sure it is closed first
            self.line_layer_selector.close()
            del self.line_layer_selector
            self.line_layer_selector = None


    def toggle_quick_map_tool(
        self,
        layer_name: str | list[str],
        mode: str,
        layers_ref: Optional[str] = None,
        prepopulate: Optional[dict[str, Any]] = None,
    ) -> bool:
        """
        Toggle the required quick map tool for the given layer and mode.
        This will automatically disable any other quick map tools which are currently active.
        Takes an optional layers_ref value which is used to name the layers the tool is used on when it is more than 1.
        Takes an optional dictionary which can be used to prepopulate values in features created by the tool.
        Returns a boolean indicating if the given tool was toggled.
        """
        # Don't validate that a field_project exists if the tool is for the layer field_project
        check_fp = True
        if layer_name == "field_project":
            check_fp = False
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True, field_project_exists=check_fp) or self.warn_unsaved_locality_data():  # noqa
            # Disable active tool if there is one and untoggle buttons to ensure things are not left in a bad state
            self.disable_current_quick_map_tool()
            self.untoggle_quick_map_tool_buttons()
            return False

        if isinstance(layer_name, str):
            toggled_quick_map_tool_name = f"fdc_{layer_name}_{mode}"
            layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        else:
            toggled_quick_map_tool_name = f"fdc_{layers_ref}_{mode}"
            layer = [
                QgsProject.instance().mapLayersByName(layer_name_)[0]
                for layer_name_ in layer_name
            ]

        # Get the current map tool before changing anything
        map_tool = self.iface.mapCanvas().mapTool()

        # If the current qgis map tool is one of our quick map tools, disable it
        # This covers the case where a user wants to toggle the tool off
        # and where the user is switching to a different quick map tool
        self.disable_current_quick_map_tool()

        # If the current qgis map tool is different to the toggled quick map tool
        # then we need to enable the toggled map tool as the user is trying to enable it
        if map_tool is None or map_tool.toolName() != toggled_quick_map_tool_name:
            self.enable_quick_map_tool(layer, mode, toggled_quick_map_tool_name, prepopulate)

        return True


    def enable_quick_map_tool(
        self,
        layer: QgsVectorLayer | list[QgsVectorLayer],
        mode: str,
        tool_name: str,
        prepopulate: Optional[dict[str, Any]] = None,
    ) -> None:
        """
        Setup the required quick map tool for the given layer and mode.
        Takes an optional dictionary which can be used to prepopulate values in features created by the tool.
        """
        mode_tools = {
            "add": QuickAddTool,
            "edit": QuickEditTool,
            "delete": QuickDeleteTool,
        }

        # Get the tools associated action
        if tool_name in self.quick_map_tool_buttons:
            action = self.quick_map_tool_buttons[tool_name]
        else:
            action = None

        self.quick_map_tool = mode_tools[mode](self.iface, layer, tool_name, action, prepopulate)

        # Connect the required signals
        self.quick_map_tool.warn_unsaved_locality_data.connect(self.warn_unsaved_locality_data)
        self.quick_map_tool.to_deactivate.connect(self.disable_current_quick_map_tool)

        self.iface.mapCanvas().setMapTool(self.quick_map_tool)


    def disable_current_quick_map_tool(self) -> None:
        """
        Disable the current map tool if it is one of our quick map tools.
        """
        map_tool = self.iface.mapCanvas().mapTool()
        # If it is one of our quick map tools
        if map_tool is not None and map_tool.toolName().startswith("fdc_"):
            # Untoggle the associated button
            # QGIS should do this automatically using .action() through .deactivate()
            # But so far I don't know whether to trust it
            if map_tool.action() is not None:
                map_tool.action().setChecked(False)
            self.iface.mapCanvas().unsetMapTool(self.iface.mapCanvas().mapTool())


    def untoggle_quick_map_tool_buttons(self) -> None:
        """
        Untoggle all of the quick map tool buttons.
        """
        for action in self.quick_map_tool_buttons.values():
            action.setChecked(False)


    def warn_unsaved_locality_data(self) -> bool:
        """
        Check if any of the locality_point related layers have unsaved changes.
        This includes both the parent locality_point layer, and all of its children.
        If they do, a warning message is shown to the user in the form of a QMessageBox.
        Returns a boolean indicating if unsaved layers were found.
        """
        unsaved_layers = []

        # Check the parent layer
        parent_layer_name = "locality_point"
        parent_layer = QgsProject.instance().mapLayersByName(parent_layer_name)[0]
        if parent_layer.isModified():
            unsaved_layers.append(parent_layer_name)

        # Check the child layers
        for layer_name in LOCALITY_POINT_CHILDREN:
            layer = QgsProject.instance().mapLayersByName(layer_name)[0]
            if layer.isModified():
                unsaved_layers.append(layer_name)

        if unsaved_layers:
            # Create the list of unsaved layer names to display in the QMessageBox
            joined_names = "\n".join(unsaved_layers)
            # Manually build the QMessageBox so we can change the icon
            message_box = QMessageBox()
            message_box.setWindowTitle("Warning")
            message_box.setText(f"There are unsaved edits on the following layer(s):\n\n{joined_names}")
            message_box.setStandardButtons(QMessageBox.Ok)
            # Get the 'Current Edits' red pencils icon as a pixmap the size of the default QMessageBox icons
            red_pencils_pixmap = self.iface.actionAllEdits().icon().pixmap(48, 48)
            # Set the icon using the pixmap
            message_box.setIconPixmap(red_pencils_pixmap)
            # Open the message box
            message_box.exec()
            return True

        return False


    def open_file_linker(self) -> bool:
        """
        Open the File Linker tool of the plugin if there are unlinked files found in the project.
        Returns a boolean indicating the success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True, field_project_exists=True):  # noqa
            return False

        self.file_linker = FileLinker()
        # If no unregistered files are found
        if self.file_linker.file_count == 0:
            self.close_file_linker()
            QMessageBox.information(None, "All Files Linked", "All of the project files are already linked.")
            return False

        else:
            self.file_linker.file_linker_closed.connect(self.close_file_linker)
            # Make it modal so changes are not made whilst importing photos
            self.file_linker.exec()

        return True


    def close_file_linker(self) -> None:
        """
        Delete the current File Linker object if there is one.
        """
        if self.file_linker is not None:
            del self.file_linker
            self.file_linker = None


    def run_project_validation(self) -> None:
        """
        Run the project validation against the current QGIS project.
        """
        if self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True):
            results = validate_project(self.project_dir)

            all_messages: list[str] = []
            result_statuses: set[ValidationStatus] = set()
            for result in results:
                result_statuses.add(result.status)

                if result.status < ValidationStatus.PASS:
                    display_messages = [
                        # Add bullet point before each message
                        "• " + message
                        for message in result.messages
                    ]
                    all_messages.append("\n".join(display_messages))

            # Get final status
            status_to_str = {
                ValidationStatus.FAIL: "failed",
                ValidationStatus.WARNING: "warning",
                ValidationStatus.PASS: "passed",
            }
            status_to_qmsgbox = {
                ValidationStatus.FAIL: QMessageBox.critical,
                ValidationStatus.WARNING: QMessageBox.warning,
                ValidationStatus.PASS: QMessageBox.information,
            }
            final_status = min(result_statuses)

            # Prepare final message for QMessageBox
            qmsgbox_msg = "\n\n".join([
                f"Validation for project '{self.project_dir.name}': {status_to_str[final_status].upper()}",
            ] + all_messages)

            status_to_qmsgbox[final_status](None, "Project Validation", qmsgbox_msg)
