# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldDataCapture
                                 A QGIS plugin
 This plugin aids with field data capture based work
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2023 by BGS Informatics
        email                : enquiries@bgs.ac.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import logging
import os.path
import pprint
import sqlite3
from collections import defaultdict
from pathlib import Path
from typing import (
    Any,
    Callable,
    Optional,
)
from xml.dom import minidom
from xml.etree.ElementTree import canonicalize

from qgis.core import (
    Qgis,
    QgsEditorWidgetSetup,
    QgsLayerTree,
    QgsLayerTreeGroup,
    QgsMapLayer,
    QgsMapLayerDependency,
    QgsProject,
    QgsRuleBasedRenderer,
    QgsSymbol,
    QgsVectorLayer,
    QgsVectorLayerUtils,
)
from qgis.gui import (
    QgisInterface,
    QgsMapTool,
)
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import (
    QColor,
    QIcon,
)
from qgis.PyQt.QtWidgets import (
    QAction,
    QMenu,
    QMessageBox,
    QWidget,
)

# Initialize Qt resources from file resources.py
from .resources import *  # noqa

from .config import (
    DICTIONARIES,
    FEATURE_TABLES,
    FEATURE_TABLES_LINES,
    INTERNAL_TABLES,
    LOCALITY_POINT_CHILDREN,
    TABLE_LIST,
    VIEWS,
)
from .create_gpkg_from_sql import main as gpkg_from_sql
from .create_gpkg_from_sql import (
    add_test_data,
    WORKDIR,
)
from .quick_map_tools import (
    QuickAddTool,
    QuickEditTool,
    QuickDeleteTool,
)
from .utils import ipdb_breakpoint  # noqa

logger = logging.getLogger('fdc')
logging.basicConfig(level=logging.DEBUG)


class FieldDataCapture:
    """QGIS Plugin Implementation."""

    def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface: QgisInterface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        # locale = QSettings().value('locale/userLocale')[0:2]
        # locale_path = os.path.join(
        #     self.plugin_dir,
        #     'i18n',
        #     'FieldDataCapture_{}.qm'.format(locale))

        # if os.path.exists(locale_path):
        #     self.translator = QTranslator()
        #     self.translator.load(locale_path)
        #     QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Field Data Capture')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.gpkg_filename = Path("field-data-capture.gpkg")

        self.quick_map_tool_buttons: dict[str, QAction] = {}
        self.quick_map_tool: Optional[QgsMapTool] = None

        logger.debug("Field Data Capture plugin initialised.")

    @property
    def project_dir(self) -> Path:
        """
        Get the current project directory.
        """
        return Path(QgsProject.instance().readPath("./"))


    @property
    def db_file(self) -> Path:
        """
        Get the db file path from the current project.
        """
        return self.project_dir / self.gpkg_filename


    @property
    def styles_dir(self) -> Path:
        """
        Get the styles directory path from the current project.
        """
        return self.project_dir / "styles"


    @property
    def icons_dir(self) -> Path:
        """
        Get the icons directory path from the plugin folder.
        """
        return WORKDIR / "icons"


    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        noinspection PyMethodMayBeStatic

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FieldDataCapture', message)


    def add_action(
        self,
        icon_path: str,
        text: str,
        callback: Callable,
        enabled_flag: bool = True,
        add_to_menu: bool = True,
        add_to_toolbar: bool = False,
        status_tip: Optional[str] = None,
        whats_this: Optional[str] = None,
        parent: Optional[QWidget] = None,
        submenu: Optional[QMenu] = None,
        checkable: bool = False,
    ) -> QAction:
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to False.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param submenu: Optional QMenu widget. The new action will be added
            to this submenu.
        :type submenu: QMenu

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.setEnabled(enabled_flag)

        if callback is not None:
            action.triggered.connect(callback)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu and submenu is None:
            self.iface.addPluginToMenu(
                self.menu,
                action,
            )

        if submenu is not None:
            submenu.addAction(action)

        if checkable:
            action.setCheckable(True)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/field_data_capture/icon.png'

        self.quick_map_tool_buttons["fdc_locality_point_add"] = self.add_action(
            str(self.icons_dir / "quick_locality_add.png"),
            text=self.tr(u'Quick Add Locality Point'),
            callback=lambda: self.toggle_quick_map_tool(layer_name="locality_point", mode="add"),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.quick_map_tool_buttons["fdc_locality_point_edit"] = self.add_action(
            str(self.icons_dir / "quick_locality_edit.png"),
            text=self.tr(u'Quick Edit Locality Point'),
            callback=lambda: self.toggle_quick_map_tool(layer_name="locality_point", mode="edit"),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.quick_map_tool_buttons["fdc_locality_point_delete"] = self.add_action(
            str(self.icons_dir / "quick_locality_delete.png"),
            text=self.tr(u'Quick Delete Locality Point'),
            callback=lambda: self.toggle_quick_map_tool(layer_name="locality_point", mode="delete"),
            add_to_toolbar=True,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Setup Project'),
            callback=lambda: self.run_function_list(functions=[
                self.add_gpkg_to_project,
                self.add_gpkg_layers_to_project,
                lambda: self.open_layer_form(layer_name="field_project"),
            ]),
            parent=self.iface.mainWindow(),
        )

        # Setup dev submenu button
        # We still create a QAction, but we set it's menu with a new QMenu
        dev_submenu_action = self.add_action(
            icon_path,
            text=self.tr(u'Developer Tools'),
            callback=None,
            parent=self.iface.mainWindow(),
        )
        dev_submenu = QMenu()
        dev_submenu_action.setMenu(dev_submenu)

        self.add_action(
            icon_path,
            text=self.tr(u'Setup Test Project'),
            callback=lambda: self.run_function_list(functions=[
                self.add_gpkg_to_project,
                self.add_gpkg_layers_to_project,
                self.add_test_data_to_project,
            ]),
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=dev_submenu,
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Export Styles to QML'),
            callback=self.export_qml_styles,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=dev_submenu,
        )

        dev_submenu.addSeparator()

        self.add_action(
            icon_path,
            text=self.tr(u'Add GeoPackage to Project'),
            callback=self.add_gpkg_to_project,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=dev_submenu,
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Add GeoPackage Layers to Project'),
            callback=self.add_gpkg_layers_to_project,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=dev_submenu,
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Add Field Project'),
            callback=lambda: self.open_layer_form(layer_name="field_project"),
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=dev_submenu,
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Add Test Data to Project'),
            callback=self.add_test_data_to_project,
            add_to_menu=False,
            parent=self.iface.mainWindow(),
            submenu=dev_submenu,
        )

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Disable the current QuickMapTool if there is one
        self.disable_current_quick_map_tool()

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Field Data Capture'),
                action)
            self.iface.removeToolBarIcon(action)


    @staticmethod
    def project_is_active() -> bool:
        """
        Check if a saved project is currently open.
        """
        if QgsProject.instance().fileName() != '':
            return True
        else:
            QMessageBox.information(None, "Information", "Please open a saved project.")
            return False


    @staticmethod
    def check_layer_exists(layer_name: str) -> bool:
        """
        Check if a given layer name exists in the list of current layers.
        """
        if len(QgsProject.instance().mapLayersByName(layer_name)) > 0:
            return True
        else:
            return False


    @staticmethod
    def check_fdc_layers_exist() -> bool:
        """
        Check if the Field Data Capture layers exist in the current layers.
        """
        missing_layers = [
            table_name
            for table_name in TABLE_LIST
            if not FieldDataCapture.check_layer_exists(table_name)
        ]
        if len(missing_layers) == 0:
            return True
        else:
            return False


    def validate_qgis_state(
        self,
        project_active: bool = False,
        db_file_exists: bool = False,
        fdc_layers_exist: bool = False,
        layer_name_exists: Optional[str] = None,
    ) -> bool:
        """
        Validate that the given options are currently OK in QGIS.
        Returns a boolean indicating the validity of the current state of QGIS.
        """
        # If we need to check project_active and the project is not active
        if project_active and not self.project_is_active():
            return False

        # If we need to check the db_file_exists and the db file does not exist
        if db_file_exists and not self.db_file.exists():
            QMessageBox.information(None, "Information", f"Could not find file:\n\n{self.db_file}")
            return False

        # If we need to check the fdc_layers_exist and the fdc layers do not exist
        if fdc_layers_exist and not self.check_fdc_layers_exist():
            QMessageBox.information(None, "Information", "Could not find the required layers for Field Data Capture.")
            return False

        # If we need to check that a given layer_name_exists and the given layer name does not exist
        if layer_name_exists is not None and not self.check_layer_exists(layer_name_exists):
            QMessageBox.information(None, "Information", f"Could not find layer: {layer_name_exists}")
            return False

        return True


    def run_function_list(self, functions: list[Callable]) -> bool:
        """
        Run all the given functions in order.
        Each function must return a boolean indicating it's success.
        If a function returns False, function execution will end.
        Returns a boolean indicating success of the process.
        """
        for function_ in functions:
            return_ = function_()
            # We don't want to continue through the setup if a process fails
            if return_ is False:
                return False

        return True


    def add_gpkg_to_project(self) -> bool:
        """
        Add the GeoPackage file to the current project.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True):
            return False

        if self.db_file.exists():
            result = QMessageBox.question(
                None, "File Already Exists",
                f"The file already exists, would you like to overwrite the file?\n\n{self.db_file}",
            )
            if result == QMessageBox.No:
                return False

        gpkg_from_sql(db_file=self.db_file)
        QMessageBox.information(None, "Information", f"Created GeoPackage:\n\n{self.db_file}")
        return True


    def add_gpkg_layers_to_project(self) -> bool:
        """
        Add the GeoPackage layers to the current project.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True):
            return False

        # Get layer tree root
        root = QgsProject.instance().layerTreeRoot()

        # Store the vector layers as keys, with it's corresponding group as the items
        vector_layers = {}
        for idx, (group_name, group_layer_names) in enumerate(self.layer_tree_structure.items()):

            # Create the group if required
            group = None
            add_to_legend = True
            if group_name is not None:
                group = self.create_legend_group(root, group_name, idx)
                add_to_legend = False

            for layer_name in group_layer_names:
                # Create layer
                uri = f"{self.db_file}|layername={layer_name}"
                vector_layer = QgsVectorLayer(uri, layer_name, "ogr")
                QgsProject.instance().addMapLayer(vector_layer, add_to_legend)
                vector_layers[vector_layer] = group

        # Changes to layers are only done after all layers are added to avoid issues
        # Create relationships first to ensure their corresponding styles/properties can be set
        self.find_create_relationships(list(vector_layers.keys()))
        self.apply_qml_styles(list(vector_layers.keys()))
        self.set_vector_layer_properties(vector_layers)
        # self.set_view_lithology_rules()

        for layer in vector_layers:
            self.refresh_relation_reference_widgets(layer)

        QMessageBox.warning(
            None, "Warning",
            "Now add a project OR test data to allow you to begin adding locality data.",
        )
        return True


    def create_legend_group(
        self,
        root: QgsLayerTree,
        group_name: str,
        idx: int,
    ) -> QgsLayerTreeGroup:
        """
        Create a group with the given name.
        Returns the new group.
        """
        # Insert a group into the layer tree at the given index
        group = root.insertGroup(idx, group_name)
        # If it is the lines group, expand it
        if group_name == "lines":
            group.setExpanded(True)
        else:
            group.setExpanded(False)
        return group


    def set_vector_layer_properties(self, vector_layers: dict[QgsVectorLayer, Optional[QgsLayerTreeGroup]]) -> None:
        """
        Set the properties for the given vector layers.
        This includes adding the layer to a group, setting read only, and setting display expressions.
        """
        for vector_layer, group in vector_layers.items():

            # Add layer to a group if required
            if group is not None:
                tree_layer = group.addLayer(vector_layer)
                # Collapse all layers added to a group
                tree_layer.setExpanded(False)

                # Set display expressions for certain layers
                display_expressions = {
                    "lithology": """attribute(get_feature('dic_rock_field', 'code', "lithology_code"), 'label')
                        + ' (' + "lithology_code" + ')'""",
                    "manmade_landform": '''"manmade_type_code"''',
                    "media": '''"media_link" + ' | ' + "notes"''',
                    "photo": '''"photo_file" + ' | ' + "notes"''',
                    "sample": '''"sample_id"''',
                    "structural_measurement": '''"structure_type_code"''',
                    "superficial_landform": '''"superficial_type_code"''',
                    "dic_rock_field": """"label" + ' (' + "code" + ')'""",
                    "_lnk_rock_project": """
                                            attribute(
                                                get_feature(
                                                    'field_project',
                                                    'uuid',
                                                    "field_project_uuid"),
                                                'short_name')

                                            + ' - ' +

                                            attribute(
                                                get_feature(
                                                    'dic_rock_field',
                                                    'code',
                                                    "rock_code"),
                                                'label')

                                            + ' - ' +

                                            "rock_code"
                                         """,
                }
                if vector_layer.name() in display_expressions:
                    vector_layer.setDisplayExpression(display_expressions[vector_layer.name()])

                # Set layer dependencies for views
                layer_dependencies = {
                    "view_lithology": "lithology",
                    "view_manmade_landform": "manmade_landform",
                    "view_structural_measurement": "structural_measurement",
                    "view_superficial_landform": "superficial_landform",
                }
                if vector_layer.name() in layer_dependencies:
                    dependent_layer = QgsProject.instance().mapLayersByName(layer_dependencies[vector_layer.name()])[0]
                    dependency = QgsMapLayerDependency(layerId=dependent_layer.id())
                    vector_layer.setDependencies([dependency])

            # Set dictionary layers to read only
            if vector_layer.name().startswith("dic"):
                vector_layer.setReadOnly()


    def refresh_relation_reference_widgets(self, layer: QgsVectorLayer) -> None:
        """
        Recreate the relation reference widgets ensuring that they use the
        layer id that corresponds to the current project relationships.
        """
        relation_manager = QgsProject.instance().relationManager()
        widgets = self.editor_widget_metadata(layer)

        for idx, field_name in enumerate(widgets):
            if widgets[field_name]["type"] == "RelationReference":
                logger.debug("Updating relation widget for %s.%s",
                             layer.name(), field_name)
                config = widgets[field_name]["config"]

                matching_relations = relation_manager.relationsByName(config['Relation'])
                if len(matching_relations) != 1:
                    msg = f"Relation name ({config['Relation']}) is not unique"
                    raise ValueError(msg)
                relation = matching_relations[0]

                config.update({'ReferencedLayerId': relation.referencedLayerId()})
                new_widget = QgsEditorWidgetSetup('RelationReference', config)
                layer.setEditorWidgetSetup(idx, new_widget)

    @staticmethod
    def editor_widget_metadata(layer: QgsVectorLayer) -> dict[str, dict[str, Any]]:
        widgets = {}

        for field in layer.fields():
            widget_setup = field.editorWidgetSetup()
            widgets[field.name()] = {
                'type': widget_setup.type(),
                'config': widget_setup.config()
            }

        return widgets

    def log_active_layer_widgets(self) -> None:
        layer = self.iface.activeLayer()
        logger.debug("Layer ID: %s", layer.id())

        for field in layer.fields():
            widget_setup = field.editorWidgetSetup()
            if widget_setup.isNull():
                logger.debug("No editor widget for field '%s'", field.name())
            else:
                widget = {
                    'field': field.name(),
                    'widget_type': widget_setup.type(),
                    'widget_config': widget_setup.config()
                }
                logger.debug('\n' + pprint.pformat(widget, indent=2, sort_dicts=False))

            if widget_setup.type() == "RelationReference":
                relation_manager = QgsProject.instance().relationManager()
                # Check for duplicate relations
                matching_relations = relation_manager.relationsByName(widget_setup.config()['Relation'])
                logger.debug('Matching relations: %s', matching_relations)

                try:
                    relation = matching_relations[0]
                    relation_metadata = {
                        'name': relation.name(),
                        'isValid': relation.isValid(),
                        'referencingLayer': relation.referencingLayer(),
                        'referencingLayerId': relation.referencingLayerId(),
                        'referencedLayer': relation.referencedLayer(),
                        'referencedLayerId': relation.referencedLayerId(),
                    }
                    msg = pprint.pformat(relation_metadata, indent=2, sort_dicts=False)
                    logger.debug('Relation metadata:\n%s', msg)
                except IndexError:
                    logger.debug('No relations defined in project')

    @property
    def layer_tree_structure(self) -> dict[Optional[str], list[str]]:
        """
        Dictionary of layer names which will represent the QGIS layer tree structure.
        """
        # Create inital structure
        layer_tree_structure = {
            None: FEATURE_TABLES.difference(FEATURE_TABLES_LINES),
            "lines": FEATURE_TABLES_LINES,
            "views": VIEWS,
            "locality_data": LOCALITY_POINT_CHILDREN,
            "metadata": DICTIONARIES.union(INTERNAL_TABLES),
        }

        # Sort the lists
        for group_name, table_set in layer_tree_structure.items():
            table_list = list(table_set)
            table_list.sort()
            layer_tree_structure[group_name] = table_list

        # Move the project layer
        project_name = "field_project"
        layer_tree_structure["metadata"].insert(0, project_name)

        return layer_tree_structure


    def apply_qml_styles(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Find and apply the QML style files for the given layers.
        """
        vector_layer_names = {
            vector_layer.name(): vector_layer
            for vector_layer in vector_layers
        }
        self.copy_plugin_files_to_project(plugin_src="styles", project_dest="styles")

        for qml_file in self.styles_dir.glob("*"):
            if qml_file.stem in vector_layer_names:
                # Apply the new style
                vector_layer_names[qml_file.stem].loadNamedStyle(str(qml_file))
                vector_layer_names[qml_file.stem].triggerRepaint()


    def find_create_relationships(self, vector_layers: list[QgsVectorLayer]) -> None:
        """
        Automatically find and create relationships between vector layers.
        """
        relation_manager = QgsProject.instance().relationManager()
        relations = relation_manager.discoverRelations([], vector_layers)
        for relation in relations:
            # Using the referencingLayer (child) creates other composition relations that are
            # unnecessary here, so the referencedLayer (parent) needs to be checked
            if relation.referencedLayer().name() == 'locality_point':
                # For QGIS relations, 0 = association (default), 1 = composition
                relation.setStrength(Qgis.RelationshipStrength(1))
            relation_manager.addRelation(relation)


    def set_view_lithology_rules(self) -> None:
        """
        Set the rules for the renderer so that the hex colours are used.
        See this stackexchange post for solution details:
        https://gis.stackexchange.com/questions/435463/rule-based-renderer-in-pyqgis?noredirect=1&lq=1
        """
        view_lithology_layer = QgsProject.instance().mapLayersByName("view_lithology")[0]

        symbol = QgsSymbol.defaultSymbol(view_lithology_layer.geometryType())
        renderer = QgsRuleBasedRenderer(symbol)
        root_rule = renderer.rootRule()

        simple_lithology_categories, simple_lithology_colours = self.get_lithology_categories_and_colours()

        for category, simple_lithology_list in simple_lithology_categories.items():
            hex_colour = simple_lithology_colours[category]

            expression = f"simple_lithology IN ({simple_lithology_list})"

            # Create the rule
            rule = root_rule.children()[0].clone()
            rule.setLabel(category)
            rule.setFilterExpression(expression)
            rule.symbol().setColor(QColor(hex_colour))
            rule.symbol().setSize(5)

            # Add the rule to the list of rules
            root_rule.appendChild(rule)

        # Delete the default rule
        root_rule.removeChildAt(0)
        view_lithology_layer.setRenderer(renderer)
        view_lithology_layer.triggerRepaint()


    def get_lithology_categories_and_colours(self) -> tuple[dict[str, str], dict[str, str]]:
        """
        Generate the lithology categories and colours from the _simple_lithology_categories table
        and the _simple_lithology table.
        The values in the categories dictionary are the list of simple lithologies in a comma separated string.
        """
        with sqlite3.connect(self.db_file) as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                    SELECT
                        slc.simple_lithology_category,
                        slc.simple_lithology,
                        sl.hex_colour
                    FROM
                        _simple_lithology_categories AS slc
                    LEFT JOIN
                        _simple_lithology AS sl ON slc.simple_lithology = sl.name
                    """
            )
            rows = cursor.fetchall()

        simple_lithology_categories = defaultdict(list)
        simple_lithology_colours = {}
        for category, lithology, hex_colour in rows:
            simple_lithology_categories[category].append(lithology)
            simple_lithology_colours[category] = hex_colour

        for category, lithology_list in simple_lithology_categories.items():
            str_list = ",".join(f"'{lithology}'" for lithology in lithology_list)
            simple_lithology_categories[category] = str_list

        return simple_lithology_categories, simple_lithology_colours


    def open_layer_form(self, layer_name: str) -> bool:
        """
        Open the attribute form for the given layer.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, layer_name_exists=layer_name):
            return False

        layer = QgsProject.instance().mapLayersByName(layer_name)[0]

        # Ensure the layer is editable
        if not layer.isEditable():
            layer.startEditing()

        # Create a new feature with automatically generated values from the layer
        feature = QgsVectorLayerUtils.createFeature(layer)
        # We have to add the new feature to the layer before it can be opened in the form
        layer.addFeature(feature)
        keep_feature = self.iface.openFeatureForm(layer, feature)

        # Only save if the user confirms the new feature
        if keep_feature:
            layer.commitChanges()
            return True
        else:
            layer.rollBack()
            return False


    def add_test_data_to_project(self) -> bool:
        """
        Add the test data set to the current project.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True):
            return False

        with sqlite3.connect(self.db_file) as conn:
            conn.enable_load_extension(True)
            add_test_data(conn)

        # Copy test data media files across into current project
        self.copy_plugin_files_to_project(plugin_src="test/data/photos", project_dest="photos")
        self.iface.mapCanvas().refresh()
        QMessageBox.information(None, "Information", f"Added test data set to:\n\n{self.db_file}")
        return True


    def copy_plugin_files_to_project(self, plugin_src: Path, project_dest: Path) -> None:
        """
        Copy the files from the given plugin source directory into the given project destination directory.
        """
        plugin_src_dir = WORKDIR / plugin_src
        project_dest_dir = self.project_dir / project_dest
        project_dest_dir.mkdir(parents=True, exist_ok=True)

        for src_file in plugin_src_dir.glob("*"):
            dest_file = project_dest_dir / src_file.name
            dest_file.write_bytes(src_file.read_bytes())


    def export_qml_styles(self) -> bool:
        """
        Export the QML styles for layers which belong to the Field Data Capture project.
        These are saved into the current project's styles directory.
        Returns a boolean indicating success of the process.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True):
            return False

        # Compare the QGIS version in the existing styles to the current QGIS version
        # Get the first existing QML style and parse it's XML
        existing_xml_style = minidom.parse(str(list(self.styles_dir.glob("*.qml"))[0]))
        existing_version = existing_xml_style.getElementsByTagName("qgis")[0].attributes["version"].value
        current_version = Qgis.version()
        if existing_version != current_version:
            result = QMessageBox.question(
                None, "Conflicting QGIS Versions",
                (
                    f"The existing QML files are from QGIS '{existing_version}', "
                    f"but you are using QGIS '{current_version}'. "
                    "Continuing will cause bad style diffs.\n\nDo you want to continue?"
                ),
            )
            if result == QMessageBox.No:
                return False

        # Export the current styles
        exported_styles = 0
        for table_name in TABLE_LIST:
            layer_style_path = self.styles_dir / (table_name + ".qml")
            # If the layer exists and a style file has already been saved for it
            if self.check_layer_exists(table_name) and layer_style_path.exists():
                exported_styles += 1

                # Save the style of the current layer
                layer = QgsProject.instance().mapLayersByName(table_name)[0]
                layer.saveNamedStyle(
                    str(layer_style_path),
                    categories=QgsMapLayer.Symbology | QgsMapLayer.Labeling | QgsMapLayer.Fields | QgsMapLayer.Forms | QgsMapLayer.MapTips,  # noqa
                )

                # Read the newly created XML file
                raw_xml = layer_style_path.read_text()
                # Canonicalize the XML data and save back to the same file
                # Set the newline manually to force LF line endings
                with open(layer_style_path, "w", newline="\n") as qml_file:
                    canonicalize(xml_data=raw_xml, out=qml_file)

        QMessageBox.information(
            None, "Information",
            f"{exported_styles} Field Data Capture styles have been exported to:\n\n{self.styles_dir}",
        )
        return True


    def toggle_quick_map_tool(self, layer_name: str, mode: str) -> bool:
        """
        Toggle the required quick map tool for the given layer and mode.
        This will automatically disable any other quick map tools which are currently active.
        Returns a boolean indicating if the given tool was toggled.
        """
        if not self.validate_qgis_state(project_active=True, db_file_exists=True, fdc_layers_exist=True) or self.warn_unsaved_locality_data():  # noqa
            # Disable active tool if there is one and untoggle buttons to ensure things are not left in a bad state
            self.disable_current_quick_map_tool()
            self.untoggle_quick_map_tool_buttons()
            return False

        toggled_quick_map_tool_name = f"fdc_{layer_name}_{mode}"
        layer = QgsProject.instance().mapLayersByName(layer_name)[0]

        # Get the current map tool before changing anything
        map_tool = self.iface.mapCanvas().mapTool()

        # If the current qgis map tool is one of our quick map tools, disable it
        # This covers the case where a user wants to toggle the tool off
        # and where the user is switching to a different quick map tool
        self.disable_current_quick_map_tool()

        # If the current qgis map tool is different to the toggled quick map tool
        # then we need to enable the toggled map tool as the user is trying to enable it
        if map_tool is None or map_tool.toolName() != toggled_quick_map_tool_name:
            self.enable_quick_map_tool(layer, mode)

        return True


    def enable_quick_map_tool(self, layer: QgsVectorLayer, mode: str) -> None:
        """
        Setup the required quick map tool for the given layer and mode.
        """
        tool_name = f"fdc_{layer.name()}_{mode}"
        mode_tools = {
            "add": QuickAddTool,
            "edit": QuickEditTool,
            "delete": QuickDeleteTool,
        }

        # Get the tools associated action
        if tool_name in self.quick_map_tool_buttons:
            action = self.quick_map_tool_buttons[tool_name]
        else:
            action = None

        self.quick_map_tool = mode_tools[mode](self.iface, layer, action)

        # Connect the required signals
        self.quick_map_tool.warn_unsaved_locality_data.connect(self.warn_unsaved_locality_data)
        self.quick_map_tool.to_deactivate.connect(self.disable_current_quick_map_tool)

        self.iface.mapCanvas().setMapTool(self.quick_map_tool)


    def disable_current_quick_map_tool(self) -> None:
        """
        Disable the current map tool if it is one of our quick map tools.
        """
        map_tool = self.iface.mapCanvas().mapTool()
        # If it is one of our quick map tools
        if map_tool is not None and map_tool.toolName().startswith("fdc_"):
            # Untoggle the associated button
            # QGIS should do this automatically using .action() through .deactivate()
            # But so far I don't know whether to trust it
            if map_tool.action() is not None:
                map_tool.action().setChecked(False)
            self.iface.mapCanvas().unsetMapTool(self.iface.mapCanvas().mapTool())


    def untoggle_quick_map_tool_buttons(self) -> None:
        """
        Untoggle all of the quick map tool buttons.
        """
        for action in self.quick_map_tool_buttons.values():
            action.setChecked(False)


    def warn_unsaved_locality_data(self) -> bool:
        """
        Check if any of the locality_point related layers have unsaved changes.
        This includes both the parent locality_point layer, and all of its children.
        If they do, a warning message is shown to the user in the form of a QMessageBox.
        Returns a boolean indicating if unsaved layers were found.
        """
        unsaved_layers = []

        # Check the parent layer
        parent_layer_name = "locality_point"
        parent_layer = QgsProject.instance().mapLayersByName(parent_layer_name)[0]
        if parent_layer.isModified():
            unsaved_layers.append(parent_layer_name)

        # Check the child layers
        for layer_name in LOCALITY_POINT_CHILDREN:
            layer = QgsProject.instance().mapLayersByName(layer_name)[0]
            if layer.isModified():
                unsaved_layers.append(layer_name)

        if unsaved_layers:
            # Create the list of unsaved layer names to display in the QMessageBox
            joined_names = "\n".join(unsaved_layers)
            # Manually build the QMessageBox so we can change the icon
            message_box = QMessageBox()
            message_box.setWindowTitle("Warning")
            message_box.setText(f"There are unsaved edits on the following layer(s):\n\n{joined_names}")
            message_box.setStandardButtons(QMessageBox.Ok)
            # Get the 'Current Edits' red pencils icon as a pixmap the size of the default QMessageBox icons
            red_pencils_pixmap = self.iface.actionAllEdits().icon().pixmap(48, 48)
            # Set the icon using the pixmap
            message_box.setIconPixmap(red_pencils_pixmap)
            # Open the message box
            message_box.exec_()
            return True

        return False
