-- Dictionary tables and their contents

BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dic_sample" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT NOT NULL,
	"translation"	TEXT,
	"status"	TEXT,
	"sigma_db_code"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

INSERT INTO gpkg_contents
VALUES('dic_sample','attributes','dic_sample','Sample type dictionary.','2023-09-15T13:21:52.679Z',NULL,NULL,NULL,NULL,NULL);

CREATE TABLE IF NOT EXISTS "dic_media" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT NOT NULL,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

INSERT INTO gpkg_contents
VALUES('dic_media','attributes','dic_media','Media type dictionary.','2023-09-15T13:21:52.679Z',NULL,NULL,NULL,NULL,NULL);

CREATE TABLE IF NOT EXISTS "dic_field_project_type" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT NOT NULL,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

INSERT INTO gpkg_contents
VALUES('dic_field_project_type','attributes','dic_field_project_type','Field project type dictionary.','2023-09-15T13:21:52.679Z',NULL,NULL,NULL,NULL,NULL);

CREATE TABLE IF NOT EXISTS "dic_manmade_landform" (
	"fid"	INTEGER NOT NULL,
	"category"	TEXT,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"status"	TEXT,
	"translation"	TEXT,
	"blackbook_code"	TEXT,
	"pre2012_sigma_code"	TEXT,
	"sigma_feature_2012"	TEXT,
	"sigma_feature_2015"	TEXT,
	"sigma_db_code"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_manmade_landform','attributes','dic_manmade_landform','Dictionary of man-made features.','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE IF NOT EXISTS "dic_locality_type" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_locality_type','attributes','dic_locality_type','Dictionary of exposure types','2023-09-15t13:21:52.679z',null,null,null,null,null);


CREATE TABLE IF NOT EXISTS "dic_structure" (
	"fid"	INTEGER NOT NULL,
	"category"	TEXT NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"status"	TEXT,
	"translation"	TEXT,
	"blackbook_code"	TEXT,
	"sigma_feature_2012"	TEXT,
	"sigma_feature_2015"	TEXT,
	"secondary_attr_category"	TEXT,
	"third_attr_category"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_structure','attributes','dic_structure','Dictionary of structure codes.','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE IF NOT EXISTS "dic_structure_secondary" (
	"fid"	INTEGER NOT NULL,
	"category"	TEXT NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"status"	TEXT,
	"translation"	TEXT,
	"sigma_2012"	TEXT,
	"sigma_2015"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_structure_secondary','attributes','dic_structure_secondary','Dictionary of structure secondary attributes.','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE IF NOT EXISTS "dic_structure_third" (
	"fid"	INTEGER NOT NULL,
	"category"	TEXT NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT NOT NULL,
	"status"	TEXT,
	"translation"	TEXT,
	"sigma_2012"	TEXT,
	"sigma_2015"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_structure_third','attributes','dic_structure_third','Dictionary of structure codes.','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE IF NOT EXISTS "dic_superficial_landform" (
	"fid"	INTEGER NOT NULL,
	"category"	TEXT,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"status"	TEXT,
	"translation"	TEXT,
	"blackbook_code"	TEXT,
	"pre2012_sigma_code"	TEXT,
	"sigma_feature_2012"	TEXT,
	"sigma_feature_2015"	TEXT,
	"sigma_db_code"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_superficial_landform','attributes','dic_superficial_landform','Dictionary of superficial codes.','2023-09-15t13:21:52.679z',null,null,null,null,null);

INSERT INTO "dic_media" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'image','Image or Photograph','','C','jbow','13/09/2023',NULL,NULL);
INSERT INTO "dic_media" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'video','Video','','C','jbow','13/09/2023',NULL,NULL);
INSERT INTO "dic_media" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'voice','Voice note','','C','jbow','13/09/2023',NULL,NULL);
INSERT INTO "dic_media" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'spreadsheet','Spreadsheet or CSV','','C','colb','09/07/2024',NULL,NULL);
INSERT INTO "dic_media" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'document','Word, PDF or Text document','','C','colb','09/07/2024',NULL,NULL);
INSERT INTO "dic_media" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'other','Other file type','','C','colb','09/07/2024',NULL,NULL);

INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'field_work','Field work','','C','jbow','04/09/2023',NULL,NULL);
INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'rapid_field_work','Rapid field work','','C','jbow','04/09/2023',NULL,NULL);
INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'remote_sensing','Derived using remote sensing resources','','C','jbow','13/09/2023',NULL,NULL);
INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'desk_compilation','Desk compilation','','C','jbow','04/09/2023',NULL,NULL);
INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'archive_upload','Archive upload','','C','jbow','04/09/2023',NULL,NULL);
INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'lab_study','Lab study','','C','jbow','04/09/2023',NULL,NULL);
INSERT INTO "dic_field_project_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'derived_from_paper','Derived from a paper map or fieldslip','','C','jbow','04/09/2023',NULL,NULL);

INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'outcrop','Outcrop','','C','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'section','Section','','C','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'quarry','Quarry','','C','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'auger_borehole','Auger/Borehole','','C','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'road_cut','Road cut','','C','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'trench','Trench','','C','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_locality_type" ("fid","code","description","translation","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'other','Other','','C','kigl','01/01/2012','jbow','13/09/2023');

INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (1,'ERRATIC','erratic','Erratic','C',NULL,'ERRAT','GGMME','Erratic','Erratic','ERR','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (2,'GLACIAL','crag_and_tail','Crag and tail','C',NULL,'GL_CG','GGBC','Crag_And_Tail','Crag_And_Tail','CRAGTAIL','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (3,'GLACIAL','drumlin','Drumlin','C',NULL,'GLDRUM','GGDD','Drumlin','Drumlin','DRUM','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (4,'GLACIAL','glacial_striae','Glacial striae','C',NULL,'GLST','GGBG','Glacial_Striae','Glacial_Striae','GLSTR','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (5,'GLACIAL','glacial_striae_directional','Glacial striae, directional','C',NULL,'GLSTI','','Glacial_Striae_Directional','Glacial_Striae_Directional','GLSTD','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (6,'GLACIAL','ice_moulded_bedrock','Ice-moulded bedrock','C',NULL,'GL_IMB','FGCB','Ice_Moulded_Bedrock','Ice_Moulded_Bedrock','ICEMOBED','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (7,'GLACIAL','kettle_hollow','Kettle hollow','C',NULL,'P_KH','','Kettle_Hollow','Kettle_Hollow','KETHOL','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (8,'GLACIAL','moriane_mound','Moraine mound','C',NULL,'GL_MM','','Moraine_Mound','Moraine_Mound','MORMOUN','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (9,'GLACIAL','nivation_hollow','Nivation hollow','C',NULL,'GL_NH','','Nivation_Hollow','Nivation_Hollow','NIVHOL','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (10,'GLACIAL','p_form','P-form','C',NULL,'GL_PF','','P_Form','P_Form','PF','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (11,'GLACIAL','roche_moutonnee','Roche moutonnee','C',NULL,'GL_RM','GGBR','Roche_Moutonnee','Roche_Moutonnee','ROMOU','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (12,'GLACIAL','roche_moutonnee_striae','Roche moutonnee with striae','C',NULL,'GL_RMS','','Roche_Moutonnee_Striae','Roche_Moutonnee_Striae','ROMOUST','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (13,'GLACIAL','s_form','S-form','C',NULL,'GL_SF','','S_Form','S_Form','SF','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (14,'GLACIAL','whaleback','Whaleback','C',NULL,'GL_WBU','','Whaleback','Whaleback','WHALE','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (15,'GLACIAL','whaleback_directional','Whaleback, directional','C',NULL,'GL_WB','','Whaleback_Directional','Whaleback_Directional','WHALDIR','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (16,'GLACIOTECTONIC','glaciotectonic_ice_flow','Glaciotectonic ice flow','C',NULL,'GLTDO','','Glaciotectonic_Ice_Flow','Glaciotectonic_Ice_Flow','GLTECICE','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (17,'GLACIOTECTONIC','glaciotectonic_ice_flow_directional','Glaciotectonic ice flow, directional','C',NULL,'GLTDD','','Glaciotectonic_Ice_Flow_Directional','Glaciotectonic_Ice_Flow_Directional','GLTECICED','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (18,'GLACIOTECTONIC','glaciotectonic_unoriented','Glaciotectonic, no orientation','C',NULL,'GLTD','','Glaciotectonic_Unoriented','Glaciotectonic_Unoriented','GLTECNO','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (19,'KARST','cavity_entrance_natural','Cavity entrance, natural','C',NULL,'P_CAV','','Cavity_Entrance_Natural','Cavity_Entrance_Natural','CAV','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (20,'KARST','doline_sinkhole','Doline or sinkhole','C',NULL,'SWH','SINK','Doline_Sinkhole','Doline_Sinkhole','DO','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (21,'KARST','spring','Spring','C',NULL,'SPRING','','Spring','Spring','SPR','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (22,'KARST','stream_sink','Stream sink','C',NULL,'P_SS','','Stream_Sink','Stream_Sink','STRSIN','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (23,'PERIGLACIAL','ice_wedge_cast','Ice wedge cast','C',NULL,'P_IWC','FIWC','Ice_Wedge_Cast','Ice_Wedge_Cast','ICEWC','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (24,'PERIGLACIAL','patterned_ground','Patterned ground','C',NULL,'P_PG','','Patterned_Ground','Patterned_Ground','PATG','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (25,'PERIGLACIAL','pingo','Pingo','C',NULL,'P_PING','','Pingo','Pingo','PIN','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (26,'PERIGLACIAL','tor','Tor','C',NULL,'P_TOR','','Tor','Tor','TO','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (27,'TOPOGRAPHIC_FEATURE','col','Col','C',NULL,'P_COL','','Col','Col','COL','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (28,'TOPOGRAPHIC_FEATURE','dune','Dune','C',NULL,'P_DUNE','','Dune','Dune','DU','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (29,'TOPOGRAPHIC_FEATURE','high_point_mound','Mound, high point','C',NULL,'P_HPT','','Mound_High_Point','High_Point_Mound','HPM','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (30,'TOPOGRAPHIC_FEATURE','low_point_hollow','Hollow, low point','C',NULL,'P_LPT','','Hollow_Point_Low','Low_Point_Hollow','LPH','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_superficial_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (31,'TOPOGRAPHIC_FEATURE','subsidence_hollow','Subsidence hollow','C',NULL,'P_SH','','Subsidence_Hollow','Subsidence_Hollow','SUBHOL','kigl','01/01/2012','jbow','08/01/2024');

INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (1,'ARTIFICIAL_POINTS','adit','Adit','C',NULL,'ADIT','ADITW','Adit','Adit','AD','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (2,'ARTIFICIAL_POINTS','adit_abandoned','Adit, abandoned','C',NULL,'ADIT_A','ADITA','Adit_Abandoned','Adit_Abandoned','ADA','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (3,'ARTIFICIAL_POINTS','adit_unknown_orientation','Adit, unknown orientation','C',NULL,'ADIT_U','','Adit_Unknown_Orientation','Adit_Unknown_Orientation','ADU','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (4,'ARTIFICIAL_POINTS','former_mine_site','Site of former mine','C',NULL,'S_FM','','Former_Mine_Site','Former_Mine_Site','SIFM','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (5,'ARTIFICIAL_POINTS','pit_underground','Pit or shaft underground','C',NULL,'PIT_UD','','','PIT_UD','PITUD','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (6,'ARTIFICIAL_POINTS','pit_fall_crownhole','Pit fall or crownhole','C',NULL,'PIT_F','','Pit_Fall_Crownhole','Pit_Fall_Crownhole','PITF','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (7,'ARTIFICIAL_POINTS','shaft','Pit or mine shaft','C',NULL,'PIT','SHAFW','Shaft','Shaft','PIT','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (8,'ARTIFICIAL_POINTS','shaft_abandoned','Pit or mine shaft, abandoned','C',NULL,'PIT_AA','SHAFA','Shaft_Abandoned','Shaft_Abandoned','PITAA','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (9,'ARTIFICIAL_POINTS','shaft_abandoned_capped','Pit or mine, abandoned and capped','C',NULL,'PIT_AC','','Shaft_Abandoned_Capped','Shaft_Abandoned_Capped','PITAC','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (10,'ARTIFICIAL_POINTS','shaft_abandoned_uncertain','Pit or mine shaft, abandoned uncertain locality','C',NULL,'PIT_U','','Shaft_Abandoned_Uncertain','Shaft_Abandoned_Uncertain','PITU','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (11,'ARTIFICIAL_POINTS','trench','Trench','C',NULL,'TRE','','Trench','Trench','TREN','kigl','01/01/2012','jbow','08/01/2024');
INSERT INTO "dic_manmade_landform" ("fid","category","code","description","status","translation","blackbook_code","pre2012_sigma_code","sigma_feature_2012","sigma_feature_2015","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (12,'ARTIFICIAL_POINTS','waste_disposal_site','Waste disposal site','C',NULL,'WASTE','','','Waste_Disposal_site','','kigl','01/01/2012','jbow','08/01/2024');

INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (1,'BEDDING','strata_inclined_1','Strata Inclined 1','C',NULL,'S_IS1','Strata_Inclined_1','Strata_Inclined_1','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (2,'BEDDING','strata_inclined_2','Strata Inclined 2','C',NULL,'S_IS2','Strata_Inclined_2','Strata_Inclined_2','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (3,'BEDDING','strata_horizontal','Strata Horizontal','C',NULL,'S_HS','Strata_Horizontal','Strata_Horizontal','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (4,'BEDDING','strata_vertical','Strata Vertical','C',NULL,'S_VS','Strata_Vertical','Strata_Vertical','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (5,'BEDDING','strata_general_dip','Strata General Dip','C',NULL,'S_GDIP','Strata_General_Dip','Strata_General_Dip','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (6,'BEDDING','strata_overturned_inclined','Strata Overturned Inclined','C',NULL,'S_ISO','Strata_Overturned_Inclined','Strata_Overturned_Inclined','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (7,'BEDDING','strata_overturned_horizontal','Strata Overturned Horizontal','C',NULL,'S_HOS','Strata_Overturned_Horizontal','Strata_Overturned_Horizontal','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (8,'BEDDING','strata_way_up_unknown_inclined','Strata Way Up Unknown Inclined','C',NULL,'S_ISU','Strata_Way_Up_Unknown_Inclined','Strata_Way_Up_Unknown_Inclined','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (9,'BEDDING','strata_way_up_unknown_horizontal','Strata Way Up Unknown Horizontal','C',NULL,'S_HSUK','Strata_Way_Up_Unknown_Horizontal','Strata_Way_Up_Unknown_Horizontal','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (10,'BEDDING','strata_inclined_underground','Strata UG Inclined','C',NULL,'S_ISU1','Strata_Inclined_Underground','Strata_Inclined_Underground','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (11,'BEDDING','strata_general_dip_underground','Strata UG General','C',NULL,'S_GDUP','Strata_General_Dip_Underground','Strata_General_Dip_Underground','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (12,'BEDDING','strata_cross_bedding_foresets','Strata Cross Bedding','C',NULL,'S_CBF','Strata_Cross_Bedding_Foresets','Strata_Cross_Bedding_Foresets','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (13,'BEDDING','strata_geopetal_infill_surface','Strata Geopetal','C',NULL,'S_CBFG','Geopetal_Infill_Surface','Strata_Geopetal_Infill_Surface','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (14,'FAULT','fault_plane_dip','Fault Dip','C',NULL,'FLT_DP','Fault_Plane_Dip','Fault_Plane_Dip','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (15,'FAULT','fault_scissor_point','Scissor Point','C',NULL,'FLT_SP','Fault_Scissor_Point','Fault_Scissor_Point','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (16,'FAULT','joint_inclined','Joint Inclined','C',NULL,'S_IJ','Joint_Inclined','Joint_Inclined','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (17,'FAULT','joint_horizontal','Joint Horizontal','C',NULL,'S_HJ','Joint_Horizontal','Joint_Horizontal','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (18,'FAULT','joint_vertical','Joint Vertical','C',NULL,'S_VJ','Joint_Vertical','Joint_Vertical','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (19,'YOUNGING','younging_direction','Younging Direction','C',NULL,'S_DY','Younging_Direction','Younging_Direction','YOUNGING_EVIDENCE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (20,'FACING','facing_direction','Facing Direction','C',NULL,'S_DC','Facing_Direction','Facing_Direction','YOUNGING_EVIDENCE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (21,'VERGENCE','vergence_direction','Vergence Direction','C',NULL,'S_DVMF','Vergence_Direction','Vergence_Direction','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (22,'VERGENCE','vergence_dextral','Vergence Dextral','C',NULL,'S_DXVM','Vergence_Dextral','Vergence_Dextral','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (23,'VERGENCE','vergence_sinistral','Vergence Sinistral','C',NULL,'S_SVMF','Vergence_Sinistral','Vergence_Sinistral','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (24,'VERGENCE','vergence_neutral','Vergence Neutral','C',NULL,'S_NVMF','Vergence_Neutral','Vergence_Neutral','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (25,'MINERAL_VEIN','mineral_vein_dip','Mineral Vein Dip','C',NULL,'S_MVFD','Mineral_Vein_Dip','Mineral_Vein_dip','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (26,'AXIAL_PLANE','axial_plane_inclined','Axial Plane Inclined','C',NULL,'S_IAPM','Axial_Plane_Inclined','Axial_Plane_Inclined','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (27,'AXIAL_PLANE','axial_plane_horizontal','Axial Plane Horizontal','C',NULL,'S_HAPM','Axial_Plane_Horizontal','Axial_Plane_Horizontal','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (28,'AXIAL_PLANE','axial_plane_vertical','Axial Plane Vertical','C',NULL,'S_VAPM','Axial_Plane_Vertical','Axial_Plane_Vertical','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (29,'FOLD_AXIS','fold_axis','Fold Axis Inclined','C',NULL,'S_AMF','Fold_Axis','Fold_Axis','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (30,'FOLD_AXIS','fold_axis_horizontal','Fold Axis Horizontal','C',NULL,'S_HAMF','Fold_Axis_Horizontal','Fold_Axis_Horizontal','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (31,'FOLD_AXIS','fold_axis_vertical','Fold Axis Vertical','C',NULL,'S_VAMF','Fold_Axis_Vertical','Fold_Axis_Vertical','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (32,'FOLD_AXIS','syncline_axis','Syncline Axis','C',NULL,'S_AMS','Syncline_Axis','Syncline_Axis','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (33,'FOLD_AXIS','syncline_axis_horizontal','Syncline Axis Horizontal','C',NULL,'S_HAMS','Syncline_Axis_Horizontal','Syncline_Axis_Horizontal','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (34,'FOLD_AXIS','anticline_axis','Anticline Axis','C',NULL,'S_AMA','Anticline_Axis','Anticline_Axis','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (35,'FOLD_AXIS','anticline_axis_horizontal','Anticline Axis Horizontal','C',NULL,'S_HAMA','Anticline_Axis_Horizontal','Anticline_Axis_Horizontal','FOLD_SHAPE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (36,'FOLIATION','foliation_penetrative_inclined','Foliation Penetrative Inclined','C',NULL,'S_IC','Foliation_Penetrative_Inclined','Foliation_Penetrative_Inclined','FOLIATION_PENETRATIVE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (37,'FOLIATION','foliation_penetrative_horizontal','Foliation Penetrative Horizontal','C',NULL,'S_HC','Foliation_Penetrative_Horizontal','Foliation_Penetrative_Horizontal','FOLIATION_PENETRATIVE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (38,'FOLIATION','foliation_penetrative_vertical','Foliation Penetrative Vertical','C',NULL,'S_VC','Foliation_Penetrative_Vertical','Foliation_Penetrative_Vertical','FOLIATION_PENETRATIVE','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (39,'FOLIATION','foliation_spaced_inclined','Foliation Spaced Inclined','C',NULL,'S_ICS','Foliation_Spaced_Inclined','Foliation_Spaced_Inclined','FOLIATION_SPACED','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (40,'FOLIATION','foliation_spaced_horizontal','Foliation Spaced Horizontal','C',NULL,'S_HCS','Foliation_Spaced_Horizontal','Foliation_Spaced_Horizontal','FOLIATION_SPACED','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (41,'FOLIATION','foliation_spaced_vertical','Foliation Spaced Vertical','C',NULL,'S_VCS','Foliation_Spaced_Vertical','Foliation_Spaced_Vertical','FOLIATION_SPACED','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (42,'FOLIATION','foliation_compositional_inclined','Foliation Compositional Inclined','C',NULL,'S_IF','Foliation_Compositional_Inclined','Foliation_Compositional_Inclined','FOLIATION_COMPOSITIONAL','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (43,'FOLIATION','foliation_compositional_horizontal','Foliation Compositional Horizontal','C',NULL,'S_HF','Foliation_Compositional_Horizontal','Foliation_Compositional_Horizontal','FOLIATION_COMPOSITIONAL','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (44,'FOLIATION','foliation_compositional_vertical','Foliation Compositional Vertical','C',NULL,'S_VF','Foliation_Compositional_Vertical','Foliation_Compositional_Vertical','FOLIATION_COMPOSITIONAL','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (45,'FOLIATION','foliation_shear_inclined','Foliation Shear Inclined','C',NULL,'S_ISZ','Foliation_Shear_Inclined','Foliation_Shear_Inclined','FOLIATION_SHEAR','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (46,'FOLIATION','foliation_shear_horizontal','Foliation Shear Horizontal','C',NULL,'S_HSZ','Foliation_Shear_Horizontal','Foliation_Shear_Horizontal','FOLIATION_SHEAR','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (47,'FOLIATION','foliation_shear_vertical','Foliation Shear Vertical','C',NULL,'S_VSZ','Foliation_Shear_Vertical','Foliation_Shear_Vertical','FOLIATION_SHEAR','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (48,'LINEATION','lineation_plunging','Lineation Plunging','C',NULL,'S_PLI','Lineation_Plunging','Lineation_Plunging','LINEATION','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (49,'LINEATION','lineation_horizontal','Lineation Horizontal','C',NULL,'S_HLI','Lineation_Horizontal','Lineation_Horizontal','LINEATION','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (50,'LINEATION','lineation_vertical','Lineation Vertical','C',NULL,'S_VLI','Lineation_Vertical','Lineation_Vertical','LINEATION','DEFORMATION_PHASE','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (51,'IGNEOUS','igneous_contact_dip','Igneous Contact Dip','C',NULL,'S_DIP','Igneous_Contact_Dip','Igneous_Contact_Dip','IGNEOUS_CONTACT','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (52,'IGNEOUS','igneous_trough_axis','Igneous Trough Axis','C',NULL,'S_ATI','Igneous_Trough_Axis','Igneous_Trough_Axis','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (53,'IGNEOUS','igneous_extrusive_planar_fabric_inclined','Ign Extrusive Planar Fabric Inclined','C',NULL,'S_IWF','Igneous_Extrusive_Planar_Fabric_Inclined','Igneous_Extrusive_Planar_Fabric_Inclined','IGNEOUS_EXTRUSIVE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (54,'IGNEOUS','igneous_extrusive_planar_fabric_horizontal','Ign Extrusive Planar Fabric Horizontal','C',NULL,'S_HWF','Igneous_Extrusive_Planar_Fabric_Horizontal','Igneous_Extrusive_Planar_Fabric_Horizontal','IGNEOUS_EXTRUSIVE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (55,'IGNEOUS','igneous_extrusive_planar_fabric_vertical','Ign Extrusive Planar Fabric Vertical','C',NULL,'S_VWF','Igneous_Extrusive_Planar_Fabric_Vertical','Igneous_Extrusive_Planar_Fabric_Vertical','IGNEOUS_EXTRUSIVE','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (56,'IGNEOUS','igneous_planar_fabric_inclined','Ign Planar Fabric Inclined','C',NULL,'S_IPP','Igneous_Planar_Fabric_Incl','Igneous_Planar_Fabric_Inclined','IGNEOUS_PLANAR','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (57,'IGNEOUS','igneous_planar_fabric_horizontal','Ign Planar Fabric Horizontal','C',NULL,'S_HPPF','Igneous_Planar_Fabric_Horiz','Igneous_Planar_Fabric_Horizontal','IGNEOUS_PLANAR','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (58,'IGNEOUS','igneous_planar_fabric_vertical','Ign Planar Fabric Vertical','C',NULL,'S_VPP','Igneous_Crystal_Align_Vert','Igneous_Planar_Fabric_Vertical','IGNEOUS_PLANAR','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (59,'IGNEOUS','igneous_crystal_alignment_inclined','Crystal Allignment Inclined','C',NULL,'S_IPCA','Igneous_Crystal_Align_Incl','Igneous_Crystal_Alignment_Inclined','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (60,'IGNEOUS','igneous_crystal_alignment_horizontal','Crystal Allignment Horizontal','C',NULL,'S_HPCA','Igneous_Crystal_Align_Horiz','Igneous_Crystal_Alignment_Horizontal','','','kigl','01/01/2012','jbow','05/09/2023');
INSERT INTO "dic_structure" ("fid","category","code","description","status","translation","blackbook_code","sigma_feature_2012","sigma_feature_2015","secondary_attr_category","third_attr_category","user_entered","date_entered","user_updated","date_updated") VALUES (61,'IGNEOUS','igneous_crystal_alignment_vertical','Crystal Allignment Vertical','C',NULL,'S_VPCA','Igneous_Crystal_Align_Vert','Igneous_Crystal_Alignment_Vertical','','','kigl','01/01/2012','jbow','05/09/2023');

INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (1,'YOUNGING_EVIDENCE','geopetal_structures','Younging Evidence - Geopetal Structures','C','','GP','Young-Geopetal','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (2,'YOUNGING_EVIDENCE','pillows','Younging Evidence - Pillows','C','','PL','Young-Pillows','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (3,'YOUNGING_EVIDENCE','cross_stratification','Younging Evidence - Cross Stratification','C','','CS','Young-XStrat','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (4,'YOUNGING_EVIDENCE','dessication_cracks','Younging Evidence - Dessication Cracks','C','','DC','Young-Dessic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (5,'YOUNGING_EVIDENCE','dewatering_structures','Younging Evidence - Dewatering Structures','C','','DS','Young-Dewater
','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (6,'YOUNGING_EVIDENCE','fossils','Younging Evidence - Fossils','C','','FS','Young-Fossils','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (7,'YOUNGING_EVIDENCE','graded_bedding','Younging Evidence - Graded Bedding','C','','GB','Young-Graded','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (8,'YOUNGING_EVIDENCE','load_structures','Younging Evidence - Load Structures','C','','LS','Young-Load','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (9,'YOUNGING_EVIDENCE','ripple_marks','Younging Evidence - Ripple Marks','C','','RM','Young-Ripple','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (10,'YOUNGING_EVIDENCE','scours_and_channels','Younging Evidence - Scours and Channels','C','','SC','Young-Scours','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (11,'YOUNGING_EVIDENCE','sole_markings','Younging Evidence - Sole Markings','C','','SM','Young-Sole','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (12,'YOUNGING_EVIDENCE','trace_fossils','Younging Evidence - Trace Fossils','C','','TF','Young-TraceFoss','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (13,'YOUNGING_EVIDENCE','vesicles','Younging Evidence - Vesicles','C','','VE','Young-Vesicles','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (14,'YOUNGING_EVIDENCE','weathering_structures','Younging Evidence - Weathering Structures','C','','WS','Young-Weathering','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (15,'YOUNGING_EVIDENCE','flute_casts','Younging Evidence - Flute Casts','C','','SF','Young-FluteCasts','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (16,'FOLD_SHAPE','closed','Fold Shape - Closed','C','','C','Shape-Closed','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (17,'FOLD_SHAPE','gentle','Fold Shape - Gentle','C','','G','Shape-Gentle','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (18,'FOLD_SHAPE','isoclinal','Fold Shape - Isoclinal','C','','I','Shape-Isoclinal','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (19,'FOLD_SHAPE','open','Fold Shape - Open','C','','O','Shape-Open','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (20,'FOLD_SHAPE','tight','Fold Shape - Tight','C','','T','Shape-Tight','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (21,'FOLIATION_PENETRATIVE','grain_flattening','Foliation Penetrative - Grain Flattening','C','','Grain Flattening','Fabric-GrainFlat','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (22,'FOLIATION_PENETRATIVE','schistosity','Foliation Penetrative - Schistosity','C','','Schistosity','Fabric-Schistosity','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (23,'FOLIATION_PENETRATIVE','slaty_cleavage','Foliation Penetrative - Slaty Cleavage','C','','Slaty Cleavage','Fabric-SlatyCleavage','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (24,'FOLIATION_SHEAR','mylonitic_phyllonitic','Foliation Shear - Mylonitic Phyllonitic','C','','Mylonitic Phyllonitic','Fabric-MylonPhylon','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (25,'FOLIATION_SHEAR','s_c_fabric','Foliation Shear - S_C Fabric','C','','S-C Fabric','Fabric-S-C','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (26,'FOLIATION_SHEAR','shear_zone_general','Foliation Shear - Shear Zone General','C','','Shear Zone General','Fabric-ShearZoneGen','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (27,'FOLIATION_SPACED','crenulation_cleavage','Foliation Spaced - Crenulation Cleavage','C','','Crenulation Cleavage','Fabric-Crenulation','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (28,'FOLIATION_SPACED','fracture_cleavage','Foliation Spaced - Fracture Cleavage','C','','Fracture Cleavage','Fabric-Fracture','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (29,'FOLIATION_SPACED','stylolitic_cleavage','Foliation Spaced - Stylolitic Cleavage','C','','Stylolitic Cleavage','Fabric-Stylolitic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (30,'FOLIATION_SPACED','pressure_cleavage','Foliation Spaced - Pressure Cleavage','C','','Pressure Cleavage','Fabric-Pressure','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (31,'FOLIATION_COMPOSITIONAL','gneissic','Foliation Compositional - Gneissic','C','','Gneissic','Fabric-Gneissic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (32,'FOLIATION_COMPOSITIONAL','stromatic','Foliation Compositional - Stromatic','C','','Stromatic','Fabric-Stromatic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (33,'FOLIATION_COMPOSITIONAL','transposed_bedding','Foliation Compositional - Transposed Bedding','C','','Transposed_Bedding','Fabric-Transposed','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (34,'IGNEOUS_CONTACT','intrusive_contact_unspecified','Foliation Compositional - Intrusive Contact Unspecified','C','','Intrusive_Contact_Unspecified','Contact-Unspecified','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (35,'IGNEOUS_CONTACT','intra_igneous_contact','Foliation Compositional - Intra_Igneous Contact','C','','Intra-Igneous_Contact','Contact-Intra-Igneous','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (36,'LINEATION','intersection','Lineation - Intersection','C','','In','Intersection-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (37,'LINEATION','crenulation','Lineation - Crenulation','C','','C','Crenulation-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (38,'LINEATION','elongation','Lineation - Elongation','C','','E','Elongation-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (39,'LINEATION','mineral','Lineation - Mineral','C','','M','Mineral-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (40,'LINEATION','boudin','Lineation - Boudin','C','','B','Boudin-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (41,'LINEATION','mullion','Lineation - Mullion','C','','Mu','Mullion-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (42,'LINEATION','rodding','Lineation - Rodding','C','','R','Rodding-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (43,'LINEATION','pencil','Lineation - Pencil','C','','P','Pencil-Lin
','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (44,'LINEATION','slickenside','Lineation - Slickenside','C','','S','Slickenside-Lin','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (45,'IGNEOUS_EXTRUSIVE','extrusive_flow_banding','Igneous Extrusive - Flow Banding','C','','','Extrus-Flow Banding','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (46,'IGNEOUS_EXTRUSIVE','extrusive_flow_foliation','Igneous Extrusive - Flow Foliation','C','','','Extrus-Flow Foliation','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (47,'IGNEOUS_EXTRUSIVE','extrusive_flow_jointing','Igneous Extrusive - Flow Jointing','C','','','Extrus-Flow Jointing','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (48,'IGNEOUS_EXTRUSIVE','extrusive_welding_foliation','Igneous Extrusive - Welding Foliation','C','','','Extrus-Welding Foliation','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (49,'IGNEOUS_EXTRUSIVE','extrusive_welding_foliation_parataxitic','Igneous Extrusive - Welding Foliation Parataxitic','C','','','Extrus-WeldFol-Parataxitic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (50,'IGNEOUS_EXTRUSIVE','extrusive_welding_foliation_eutaxitic','Igneous Extrusive - Welding Foliation Eutaxitic','C','','','Extrus-WeldFol-Eutaxitic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (51,'IGNEOUS_PLANAR','planar_flow_banding','Igneous Planar - Flow Banding','C','','IFB','Planar-Flow Banding','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (52,'IGNEOUS_PLANAR','planar_flow_foliation','Igneous Planar - Flow Foliation','C','','PF','Planar-Flow Foliation','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (53,'IGNEOUS_PLANAR','planar_flow_jointing','Igneous Planar - Flow Jointing','C','','PFJ','Planar-Flow Jointing','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (54,'IGNEOUS_PLANAR','planar_welding_foliation','Igneous Planar - Welding Foliation','C','','PW','Welding Foliation','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (55,'IGNEOUS_PLANAR','planar_welding_foliation_parataxitic','Igneous Planar - Welding Foliation Parataxitic','C','','PWP','Weld-Foliation-Parataxitic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (56,'IGNEOUS_PLANAR','planar_welding_foliation_eutaxitic','Igneous Planar - Welding Foliation Eutaxitic','C','','PWE','Weld-Foliation-Eutaxitic','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (57,'IGNEOUS_PLANAR','relict_planar_fabric','Igneous Planar - Relict Planar fabric','C','','PR','Relict Planar fabric','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (58,'IGNEOUS_PLANAR','compositional_layering_unspec','Igneous Planar - Compositional Layering Unspec','C','','PL','Comp-Layer-Unspec','kigl','01/01/2012','jbow','21/09/2023');
INSERT INTO "dic_structure_secondary" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (59,'IGNEOUS_PLANAR','compositional_layering_cumulate','Igneous Planar - Compositional Layering Cumulate','C','','PLC','Comp-Layer-Cumulate','kigl','01/01/2012','jbow','21/09/2023');

INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (1,'DEFORMATION_PHASE','phase_d0','Phase D0 - Primary Syndepositional/Syn Sedimentary','C','','8','Phase-D0','kigl','01/01/2012','jbow','05/03/2024');
INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (2,'DEFORMATION_PHASE','phase_d1','Phase D1','C','','1','Phase-D1','kigl','01/01/2012','jbow','05/03/2024');
INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (3,'DEFORMATION_PHASE','phase_d2','Phase D2','C','','2','Phase-D2','kigl','01/01/2012','jbow','05/03/2024');
INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (4,'DEFORMATION_PHASE','phase_d3','Phase D3','C','','3','Phase-D3','kigl','01/01/2012','jbow','05/03/2024');
INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (5,'DEFORMATION_PHASE','phase_d4','Phase D4','C','','4','Phase-D4','kigl','01/01/2012','jbow','05/03/2024');
INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (6,'DEFORMATION_PHASE','phase_d5','Phase D5','C','','5','Phase-D5','kigl','01/01/2012','jbow','05/03/2024');
INSERT INTO "dic_structure_third" ("fid","category","code","description","status","translation","sigma_2012","sigma_2015","user_entered","date_entered","user_updated","date_updated") VALUES (7,'DEFORMATION_PHASE','phase_d6','Phase D6','C','','6','Phase-D6','kigl','01/01/2012','jbow','05/03/2024');

INSERT INTO "dic_sample" ("fid","code","description","translation","status","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (1,'fossil_sample','Fossil sample','','C','FOSS','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_sample" ("fid","code","description","translation","status","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (2,'hand_specimen','Hand specimen','','C','HAND','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_sample" ("fid","code","description","translation","status","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (3,'bedrock_sample','Bedrock sample','','C','ROCK','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_sample" ("fid","code","description","translation","status","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (4,'soil_sample','Soil sample','','C','SOIL','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_sample" ("fid","code","description","translation","status","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (5,'stream_sediment_sample','Stream sediment sample','','C','STREAM','kigl','01/01/2012','jbow','13/09/2023');
INSERT INTO "dic_sample" ("fid","code","description","translation","status","sigma_db_code","user_entered","date_entered","user_updated","date_updated") VALUES (6,'superficial_deposit_sample','Superficial deposit sample','','C','SUPER','kigl','01/01/2012','jbow','13/09/2023');

COMMIT;
