/*
This file contains dictionaries and other data required for the lithology
selection to work.  It includes base dictionaries, a linking table
between projects and lithologies and views and triggers to bring things
together.

See issues #44 and #87 for context.
*/
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "_dic_rock_all" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"translation"	TEXT,
	"status"	TEXT,
	"rcs_status"  TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "dic_rock_field" (
	"fid"	INTEGER NOT NULL,
	"category"	TEXT,
	"code"	TEXT NOT NULL UNIQUE,
	"is_default"	BOOLEAN NOT NULL DEFAULT 0,
	"simple_lithology"	TEXT,
	"label" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"composite"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	FOREIGN KEY("code") REFERENCES "_dic_rock_all"("code"),
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_rock_field','attributes','dic_rock_field','Supplementary rock data for aiding field selection','2023-09-15t13:21:52.679z',null,null,null,null,null);

/*
Data created from Excel file Dic_Rock_Field_RCS__Subset_MK240124.xls, sent by email that day.

See issue #44 for more details.
*/
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (1,'ARTDP','ARTIFICIAL DEPOSIT','ARTIFICIAL DEPOSIT','Artificial deposit','SINGLE','ARTIFICIALLY MODIFIED GROUND','ARTIFICIAL DEPOSIT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (2,'CAT','FAULT ROCKS','CATACLASITE','Cataclasite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','MECHANICALLY BROKEN AND RECONSTITUTED ROCK (METAMORPHIC)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (3,'FBRC','FAULT ROCKS','FAULT-BRECCIA','Fault-breccia','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','MECHANICALLY BROKEN AND RECONSTITUTED ROCK (METAMORPHIC)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (4,'FGOUGE','FAULT ROCKS','FAULT-GOUGE','Fault-gouge','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','MECHANICALLY BROKEN AND RECONSTITUTED ROCK (METAMORPHIC)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (5,'MYLO','FAULT ROCKS','MYLONITE','Mylonite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','MECHANICALLY BROKEN AND RECONSTITUTED ROCK (METAMORPHIC)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (6,'AGG','IGNEOUS-VOLCANIC ROCK','AGGLOMERATE','Agglomerate','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (7,'AND','IGNEOUS ROCK','ANDESITE','Andesite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',1,'andesite','fine grained igneous rock; intermediate composition igneous rock; igneous rock; intermediate composition igneous material; igneous material; rock; compound material; ','#B14801','jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (8,'BA','IGNEOUS ROCK','BASALT','Basalt','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',1,'basalt','basic igneous rock; fine grained igneous rock; basic igneous material; igneous rock; igneous material; rock; compound material; volcanic rock;','#DDB397','jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (9,'BAR','IGNEOUS ROCK','BASALTIC-ROCK','Basaltic-rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (10,'DI','IGNEOUS ROCK','DIORITE','Diorite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (11,'DUN','IGNEOUS ROCK','DUNITE','Dunite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (12,'FELS','IGNEOUS ROCK','FELSITE','Felsite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (13,'GB','IGNEOUS ROCK','GABBRO','Gabbro','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (14,'GBR','IGNEOUS ROCK','GABBROIC-ROCK','Gabbroic-rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (15,'GN','IGNEOUS ROCK','GRANITE','Granite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (16,'GNR','IGNEOUS ROCK','GRANITIC-ROCK','Granitic-rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (17,'GD','IGNEOUS ROCK','GRANODIORITE','Granodiorite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (18,'IGRU','IGNEOUS ROCK','IGNEOUS ROCK','Igneous rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (19,'MFIR','IGNEOUS ROCK','IGNEOUS-ROCK, MAFIC','Mafic igneous-rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (20,'IBREC','IGNEOUS ROCK','INTRUSION-BRECCIA','Intrusion-breccia','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SILICICLASTIC SEDIMENTS AND SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (21,'LMPY','IGNEOUS ROCK','LAMPROPHYRES','Lamprophyres','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (22,'LPST','IGNEOUS-VOLCANIC ROCK','LAPILLISTONE','Lapillistone','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (23,'LPTUF','IGNEOUS-VOLCANIC ROCK','LAPILLI-TUFF','Lapilli-tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (24,'ANLTUF','IGNEOUS-VOLCANIC ROCK','LAPILLI-TUFF, ANDESITIC','Andesitic lapilli-tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (25,'DALTUF','IGNEOUS-VOLCANIC ROCK','LAPILLI-TUFF, DACITIC','Dacitic lapilli-tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (26,'RYLTUF','IGNEOUS-VOLCANIC ROCK','LAPILLI-TUFF, RHYOLITIC','Rhyolitic lapilli-tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (27,'LAVA','IGNEOUS ROCK','LAVA','Lava','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (28,'BCLAVA','IGNEOUS ROCK','LAVA, BASALTIC','Basaltic lava','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (29,'MAFI','IGNEOUS ROCK','MAFITE','Mafite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (30,'MCDI','IGNEOUS ROCK','MICRODIORITE','Microdiorite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (31,'MCGB','IGNEOUS ROCK','MICROGABBRO','Microgabbro','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (32,'MCGN','IGNEOUS ROCK','MICROGRANITE','Microgranite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (33,'MCGD','IGNEOUS ROCK','MICROGRANODIORITE','Microgranodiorite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (34,'PEG','IGNEOUS ROCK','PEGMATITE','Pegmatite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (35,'PYRR','IGNEOUS-VOLCANIC ROCK','PYROCLASTIC-ROCK','Pyroclastic-rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (36,'RY','IGNEOUS ROCK','RHYOLITE','Rhyolite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (37,'SY','IGNEOUS ROCK','SYENITE','Syenite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (38,'TPH','IGNEOUS-VOLCANIC ROCK','TEPHRA  (PYROCLASTIC SEDIMENT)','Tephra  (synonymous with pyroclastic sediment)','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (39,'TO','IGNEOUS ROCK','TONALITE','Tonalite','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (40,'TR','IGNEOUS ROCK','TRACHYTE','Trachyte','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (41,'TUF','IGNEOUS-VOLCANIC ROCK','TUFF','Tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',1,'ash tuff lapillistone and lapilli tuff','pyroclastic rock; fragmental igneous rock; fragmental igneous material; igneous rock; igneous material; pyroclastic material; ','#FFF5DF','jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (42,'ANDTFF','IGNEOUS-VOLCANIC ROCK','TUFF, ANDESITIC','Andesitic tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (43,'BASTUF','IGNEOUS-VOLCANIC ROCK','TUFF, BASALT','Basalt tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (44,'FTUFF','IGNEOUS-VOLCANIC ROCK','TUFF, FELSIC','Felsic tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (45,'MFTUF','IGNEOUS-VOLCANIC ROCK','TUFF, MAFIC','Mafic tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (46,'RYTUF','IGNEOUS-VOLCANIC ROCK','TUFF, RHYOLITIC','Rhyolitic tuff','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (47,'UMR','IGNEOUS ROCK','ULTRAMAFIC-ROCK','Ultramafic-rock','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','CRYSTALLINE-IGNEOUS-ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (48,'VCBR','IGNEOUS-VOLCANIC ROCK','VOLCANICLASTIC-BRECCIA','Volcaniclastic-breccia','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (49,'VCSST','IGNEOUS-VOLCANIC ROCK','VOLCANICLASTIC-SANDSTONE','Volcaniclastic-sandstone','SINGLE','IGNEOUS ROCK AND IGNEOUS SEDIMENT','FRAGMENTAL IGNEOUS ROCK AND FRAGMENTAL IGNEOUS SEDIMENT',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (50,'AMPHB','METAMORPHIC ROCK','AMPHIBOLITE','Amphibolite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (51,'CALSIR','METAMORPHIC ROCK','CALCSILICATE-ROCK','Calcsilicate-rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (52,'GNSS','METAMORPHIC ROCK','GNEISS','Gneiss','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (53,'HNFELS','METAMORPHIC ROCK','HORNFELS','Hornfels','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','CONTACT METAMORPHIC ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (54,'MARBLE','METAMORPHIC ROCK','MARBLE','Marble','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (55,'MBA','METAMORPHIC ROCK','METABASALT','Metabasalt','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (56,'MBAR','METAMORPHIC ROCK','METABASALTIC-ROCK','Metabasaltic-rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (57,'MCABR','METAMORPHIC ROCK','METACARBONATE-ROCK','Metacarbonate-rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (58,'MCONG','METAMORPHIC ROCK','METACONGLOMERATE','Metaconglomerate','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (59,'MGB','METAMORPHIC ROCK','METAGABBRO','Metagabbro','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (60,'MGN','METAMORPHIC ROCK','METAGRANITE','Metagranite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (61,'MGD','METAMORPHIC ROCK','METAGRANODIORITE','Metagranodiorite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (62,'MIGRU','METAMORPHIC ROCK','META-IGNEOUS ROCK','Meta-igneous rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (63,'MLMST','METAMORPHIC ROCK','METALIMESTONE','Metalimestone','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (64,'MMR','METAMORPHIC ROCK','METAMAFIC-ROCK','Metamafic-rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH IGNEOUS PROTOLITH BASED ON MODAL COMPOSITION',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (65,'MMST','METAMORPHIC ROCK','METAMUDSTONE','Metamudstone','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (66,'MRY','METAMORPHIC ROCK','METARHYOLITE','Metarhyolite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (67,'MSDST','METAMORPHIC ROCK','METASANDSTONE','Metasandstone','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (68,'MTO','METAMORPHIC ROCK','METATONALITE','Metatonalite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (69,'MULMR','METAMORPHIC ROCK','METAULTRAMAFIC-ROCK','Metaultramafic-rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (70,'MVCSR','METAMORPHIC ROCK','METAVOLCANICLASTIC SEDIMENTARY ROCK','Metavolcaniclastic sedimentary rock','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METACRYSTALLINE-IGNEOUS ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (71,'OAMPHB','METAMORPHIC ROCK','ORTHO-AMPHIBOLITE','Ortho-amphibolite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH IGNEOUS PROTOLITH BASED ON MODAL COMPOSITION',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (72,'OGNSS','METAMORPHIC ROCK','ORTHOGNEISS','Orthogneiss','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH IGNEOUS PROTOLITH BASED ON TEXTURAL ATTRIBUTES',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (73,'OGNSF','METAMORPHIC ROCK','ORTHOGNEISS, FELSIC','Felsic orthogneiss','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH IGNEOUS PROTOLITH BASED ON TEXTURAL ATTRIBUTES',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (74,'OGNSM','METAMORPHIC ROCK','ORTHOGNEISS, MAFIC','Mafic orthogneiss','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH IGNEOUS PROTOLITH BASED ON TEXTURAL ATTRIBUTES',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (75,'PEL','METAMORPHIC ROCK','PELITE','Pelite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (76,'PELGP','METAMORPHIC ROCK','PELITE, GRAPHITIC','Graphitic pelite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (77,'PSAMM','METAMORPHIC ROCK','PSAMMITE','Psammite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (78,'PSAMI','METAMORPHIC ROCK','PSAMMITE, MICACEOUS','Micaceous psammite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (79,'QZITE','METAMORPHIC ROCK','QUARTZITE','Quartzite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (80,'HBSCH','METAMORPHIC ROCK','SCHIST, HORNBLENDE','Hornblende schist','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (81,'SEMPEL','METAMORPHIC ROCK','SEMIPELITE','Semipelite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (82,'SPELGN','METAMORPHIC ROCK','SEMIPELITE, GNEISSOSE','Gneissose semipelite','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METASEDIMENT AND METASEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (83,'SLTE','METAMORPHIC ROCK','SLATE','Slate','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (84,'SCH','METAMORPHIC ROCK','SCHIST','Schist','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (85,'SCHM','METAMORPHIC ROCK','SCHIST, MICA','Mica schist','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (86,'SCHGR','METAMORPHIC ROCK','SCHIST, GRAPHITIC','Graphitic schist','SINGLE','METAMORPHIC ROCKS AND METASEDIMENTS','METAMORPHIC ROCKS WITH UNKNOWN PROTOLITH',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (87,'ANHY','SEDIMENTARY ROCK','ANHYDRITE-STONE','Anhydrite-stone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCKS AND SEDIMENTS COMPOSED OF NON-CARBONATE SALTS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (88,'BREC','SEDIMENTARY ROCK','BRECCIA','Breccia','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SILICICLASTIC SEDIMENTS AND SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (89,'CHLK','SEDIMENTARY ROCK','CHALK','Chalk','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','CARBONATE SEDIMENTS AND CARBONATE SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (90,'CHRT','SEDIMENTARY ROCK','CHERT','Chert','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','NON-CLASTIC SILICEOUS SEDIMENTS AND NON-CLASTIC SILICEOUS SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (91,'COAL','SEDIMENTARY ROCK','COAL','Coal','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTS AND SEDIMENTARY ROCKS RICH IN ORGANIC MATTER',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (92,'CONG','SEDIMENTARY ROCK','CONGLOMERATE','Conglomerate','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (93,'DOLO','SEDIMENTARY ROCK','DOLOSTONE','Dolostone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','CARBONATE SEDIMENTS AND CARBONATE SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (94,'DURI','SEDIMENTARY ROCK','DURICRUST','Duricrust','SINGLE','NATURAL SUPERFICIAL DEPOSIT','RESIDUAL DEPOSITS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (95,'FECRTE','SEDIMENTARY ROCK','FERRICRETE (IRON LATERITE/IRON PAN)','Ferricrete (iron laterite/iron pan)','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','MISC-HYDROXIDE, OXIDE AND SILICATE SEDIMENTS AND MISC-HYDROXIDE, OXIDE AND SILICATE SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (96,'GYPS','SEDIMENTARY ROCK','GYPSUM','Gypsum','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCKS AND SEDIMENTS COMPOSED OF NON-CARBONATE SALTS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (97,'HALIST','SEDIMENTARY ROCK','HALITE-STONE','Halite-stone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCKS AND SEDIMENTS COMPOSED OF NON-CARBONATE SALTS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (98,'FEST','SEDIMENTARY ROCK','IRONSTONE','Ironstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','IRON-SEDIMENTS AND IRONSTONES',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (99,'FEOOL','SEDIMENTARY ROCK','IRONSTONE, OOIDAL','Ooidal ironstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','IRON-SEDIMENTS AND IRONSTONES',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (100,'LMST','SEDIMENTARY ROCK','LIMESTONE','Limestone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','CARBONATE SEDIMENTS AND CARBONATE SEDIMENTARY ROCKS',1,'limestone','calcareous carbonate sedimentary rock; pure carbonate sedimentary rock; calcareous carbonate sedimentary material; carbonate sedimentary rock; carbonate sedimentary material; sedimentary material; compound material; sedimentary rock; rock; sedimentary material;','#149EF8','jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (101,'DOLMST','SEDIMENTARY ROCK','LIMESTONE, DOLOMITIC','Dolomitic limestone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','CARBONATE SEDIMENTS AND CARBONATE SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (102,'FLMST','SEDIMENTARY ROCK','LIMESTONE, FERRUGINOUS','Ferruginous limestone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','CARBONATE SEDIMENTS AND CARBONATE SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (103,'LMOOL','SEDIMENTARY ROCK','LIMESTONE, OOIDAL','Ooidal limestone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','CARBONATE SEDIMENTS AND CARBONATE SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (104,'MDST','SEDIMENTARY ROCK','MUDSTONE','Mudstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (105,'CAMDST','SEDIMENTARY ROCK','MUDSTONE, CALCAREOUS','Calcareous mudstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (106,'SAMDST','SEDIMENTARY ROCK','MUDSTONE, SANDY','Sandy mudstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (107,'OILS','SEDIMENTARY ROCK','OILSHALE','Oilshale','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTS AND SEDIMENTARY ROCKS RICH IN ORGANIC MATTER',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (108,'SDST','SEDIMENTARY ROCK','SANDSTONE','Sandstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (109,'CALSST','SEDIMENTARY ROCK','SANDSTONE, CALCAREOUS','Calcareous sandstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (110,'GLSST','SEDIMENTARY ROCK','SANDSTONE, GLAUCONITIC','Glauconitic sandstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (111,'MDSST','SEDIMENTARY ROCK','SANDSTONE, MUDDY','Muddy sandstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (112,'PESST','SEDIMENTARY ROCK','SANDSTONE, PEBBLY','Pebbly sandstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (113,'SLSST','SEDIMENTARY ROCK','SANDSTONE, SILTY','Silty sandstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (114,'SEAT','SEDIMENTARY ROCK','SEATEARTH','Seatearth','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (115,'CLCRET','SEDIMENTARY ROCK','SILICATE-CONGLOMERATE, CALCITE-CEMENTED (CALCRETE)','Calcite-cemented silicate-conglomerate (calcrete)','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SILICICLASTIC SEDIMENTS AND SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (116,'SICRET','SEDIMENTARY ROCK','SILICATE-CONGLOMERATE, SILICA-CEMENTED (SILCRETE)','Silcrete: silica-cemented silicate-conglomerate','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SILICICLASTIC SEDIMENTS AND SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (117,'SLST','SEDIMENTARY ROCK','SILTSTONE','Siltstone','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SEDIMENTARY ROCK',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (118,'B','SUPERFICIAL DEPOSIT','BOULDERS (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Boulders','SINGLE','NATURAL SUPERFICIAL DEPOSIT','BOULDERS [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (119,'C','SUPERFICIAL DEPOSIT','CLAY (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Clay','SINGLE','NATURAL SUPERFICIAL DEPOSIT','CLAY [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (120,'CZ','SUPERFICIAL DEPOSIT','CLAY, SILTY (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Silty clay','SINGLE','NATURAL SUPERFICIAL DEPOSIT','CLAY [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (121,'L','SUPERFICIAL DEPOSIT','COBBLES (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Cobbles','SINGLE','NATURAL SUPERFICIAL DEPOSIT','COBBLES [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (122,'DMTN','SUPERFICIAL DEPOSIT','DIAMICTON','Diamicton','SINGLE','SEDIMENT AND SEDIMENTARY ROCK','SILICICLASTIC SEDIMENTS AND SEDIMENTARY ROCKS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (123,'V','SUPERFICIAL DEPOSIT','GRAVEL (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Gravel','SINGLE','NATURAL SUPERFICIAL DEPOSIT','GRAVEL [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (124,'P','SUPERFICIAL DEPOSIT','PEAT (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Peat','SINGLE','NATURAL SUPERFICIAL DEPOSIT','PEAT [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (125,'REGOL','SUPERFICIAL DEPOSIT','REGOLITH','Regolith','SINGLE','NATURAL SUPERFICIAL DEPOSIT','RESIDUAL DEPOSITS',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (126,'ROCK','SUPERFICIAL DEPOSIT','ROCK','Rock unspecified','SINGLE','ROCK',NULL,0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (127,'S','SUPERFICIAL DEPOSIT','SAND (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Sand','SINGLE','NATURAL SUPERFICIAL DEPOSIT','SAND [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (128,'SV','SUPERFICIAL DEPOSIT','SAND, GRAVELLY (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Gravelly sand','SINGLE','NATURAL SUPERFICIAL DEPOSIT','SAND [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (129,'Z','SUPERFICIAL DEPOSIT','SILT (UNCONSOLIDATED DEPOSITS CLASSIFICATION SCHEME)','Silt','SINGLE','NATURAL SUPERFICIAL DEPOSIT','SILT [UNLITHIFIED DEPOSITS CODING SCHEME]',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (130,'VBA','VEIN ROCK','BARYTE (VEIN)','Baryte (vein)','SINGLE','VEIN ROCK','BARYTE (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (131,'VQBR','VEIN ROCK','BRECCIA, QUARTZ (VEIN)','Quartz breccia (vein)','SINGLE','VEIN ROCK','BRECCIA, QUARTZ (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (132,'VCU','VEIN ROCK','COPPER (VEIN)','Copper (vein)','SINGLE','VEIN ROCK','COPPER (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (133,'VHEM','VEIN ROCK','HEMATITE (VEIN)','Hematite (vein)','SINGLE','VEIN ROCK','HEMATITE (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (134,'VFE','VEIN ROCK','IRON (VEIN)','Iron (vein)','SINGLE','VEIN ROCK','IRON (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (135,'VPB','VEIN ROCK','LEAD (VEIN)','Lead (vein)','SINGLE','VEIN ROCK','LEAD (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (136,'VNPZ','VEIN ROCK','LEAD-ZINC (VEIN)','Lead-zinc (vein)','SINGLE','VEIN ROCK','LEAD-ZINC (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (137,'VPYR','VEIN ROCK','PYRITE (VEIN)','Pyrite (vein)','SINGLE','VEIN ROCK','PYRITE (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (138,'VQ','VEIN ROCK','QUARTZ (VEIN)','Quartz (vein)','SINGLE','VEIN ROCK','QUARTZ (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (139,'MROC','VEIN ROCK','ROCK, MINERALIZED','Mineralized rock unspecified','SINGLE','ROCK, MINERALIZED',NULL,0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (140,'VU','VEIN ROCK','URANIUM (VEIN)','Uranium (vein)','SINGLE','VEIN ROCK','URANIUM (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
INSERT INTO "dic_rock_field" ("fid","code","category","description","translation","composite","rank01_desc","rank02_desc","is_default","simple_lithology","simple_lithology_parents","hex_colour","user_entered","date_entered","user_updated","date_updated") VALUES (141,'VZN','VEIN ROCK','ZINC (VEIN)','Zinc (vein)','SINGLE','VEIN ROCK','ZINC (VEIN)',0,NULL,NULL,NULL,'jostev','2024-01-29 18:58:06',NULL,NULL);
COMMIT;