-- Dictionaries used to constrain line features.
BEGIN TRANSACTION;

CREATE TABLE "dic_line_type_artificial" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
    "status"	TEXT,
 	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_artificial','attributes','dic_line_type_artificial','Dictionary of artificial line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_bedrock" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
    "description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
    "status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_bedrock','attributes','dic_line_type_bedrock','Dictionary of bedrock line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_superficial" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
    "comments" TEXT,
	"status"	TEXT,
    "sec_attrib_list"  TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_superficial','attributes','dic_line_type_superficial','Dictionary of superficial line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_mass_move" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_mass_move','attributes','dic_line_type_mass_move','Dictionary of mass movement line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_terrain" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_terrain','attributes','dic_line_type_terrain','Dictionary of terrain line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'artificial_geology_boundary','ARTIFICIAL_GROUND_BOUNDARY','artificial_geology_boundary','artificial_geology_boundary','none yet',NULL,'C','KIGL','26/11/2023 12:16:00',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'artificial_polygon_closure','ARTIFICIAL_GROUND_BOUNDARY','artificial_polygon_closure','artificial_polygon_closure','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'cliffline_quarry','ARTIFICIAL_GROUND_LINE','cliffline_quarry','cliffline_quarry','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'limit_subsurface_mining','ARTIFICIAL_GROUND_LINE','limit_subsurface_mining','limit_subsurface_mining','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'mine_tunnel_drift_cross_measures','ARTIFICIAL_GROUND_LINE','mine_tunnel_drift_cross_measures','mine_tunnel_drift_cross_measures','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'mine_tunnel_road_in seam','ARTIFICIAL_GROUND_LINE','mine_tunnel_road_in seam','mine_tunnel_road_in seam','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'small_quarry_or_pit','ARTIFICIAL_GROUND_LINE','small_quarry_or_pit','small_quarry_or_pit','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'algal_band','BEDROCK_LINE','algal_band','algal_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'ash_band_tonstein','BEDROCK_LINE','ash_band_tonstein','ash_band_tonstein','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'base_of_lava_flow','BEDROCK_LINE','base_of_lava_flow','base_of_lava_flow','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'bedrock_geology_boundary_grad','BEDROCK_BOUNDARY','bedrock_geology_boundary_grad','bedrock_geology_boundary_grad','none',NULL,'C','KIGL','21/11/2023 14:52:25',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'bedrock_geology_boundary_inf','BEDROCK_BOUNDARY','bedrock_geology_boundary_inf','bedrock_geology_boundary_inf','none',NULL,'C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'bedrock_geology_boundary_obs','BEDROCK_BOUNDARY','bedrock_geology_boundary_obs','bedrock_geology_boundary_obs','none',NULL,'C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'bedrock_offshore_closure','BEDROCK_BOUNDARY','bedrock_offshore_closure','bedrock_offshore_closure','none',NULL,'C','KIGL','21/11/2023 15:51:03',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (8,'bedrock_polygon_closure','BEDROCK_BOUNDARY','bedrock_polygon_closure','bedrock_polygon_closure','none',NULL,'C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'bone_bed','BEDROCK_LINE','bone_bed','bone_bed','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (10,'brachiopod_band','BEDROCK_LINE','brachiopod_band','brachiopod_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (11,'cementstone_bed','BEDROCK_LINE','cementstone_bed','cementstone_bed','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (12,'coal_seam_inf','BEDROCK_LINE','coal_seam_inf','coal_seam_inf','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (13,'coal_seam_obs','BEDROCK_LINE','coal_seam_obs','coal_seam_obs','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (14,'coral_band','BEDROCK_LINE','coral_band','coral_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (15,'ductile_shear_inf','FAULT_TRACE','ductile_shear_inf','ductile_shear_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (16,'ductile_shear_obs','FAULT_TRACE','ductile_shear_obs','ductile_shear_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (17,'dyke_linear_inf','BEDROCK_LINE','dyke_linear_inf','dyke_linear_inf','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (18,'dyke_linear_obs','BEDROCK_LINE','dyke_linear_obs','dyke_linear_obs','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (19,'euestheria_band','BEDROCK_LINE','euestheria_band','euestheria_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (20,'fault_complex_movenent_inf','FAULT_TRACE','fault_complex_movenent_inf','fault_complex_movenent_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (21,'fault_complex_movenent_obs','FAULT_TRACE','fault_complex_movenent_obs','fault_complex_movenent_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (22,'fault_dextral_inf','FAULT_TRACE','fault_dextral_inf','fault_dextral_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (23,'fault_dextral_obs','FAULT_TRACE','fault_dextral_obs','fault_dextral_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (24,'fault_inf_crossmark_on_downthrow_side','FAULT_TRACE','fault_inf_crossmark_on_downthrow_side','fault_inf_crossmark_on_downthrow_side','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (25,'fault_inf_throw_unknown','FAULT_TRACE','fault_inf_throw_unknown','fault_inf_throw_unknown','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (26,'fault_normal_inf','FAULT_TRACE','fault_normal_inf','fault_normal_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (27,'fault_normal_obs','FAULT_TRACE','fault_normal_obs','fault_normal_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (28,'fault_obs_crossmark_on_downthrow_side','FAULT_TRACE','fault_obs_crossmark_on_downthrow_side','fault_obs_crossmark_on_downthrow_side','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (29,'fault_obs_throw_unknown','FAULT_TRACE','fault_obs_throw_unknown','fault_obs_throw_unknown','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (30,'fault_reverse_inf','FAULT_TRACE','fault_reverse_inf','fault_reverse_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (31,'fault_reverse_obs','FAULT_TRACE','fault_reverse_obs','fault_reverse_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (32,'fault_sinistral_inf','FAULT_TRACE','fault_sinistral_inf','fault_sinistral_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (33,'fault_sinistral_obs','FAULT_TRACE','fault_sinistral_obs','fault_sinistral_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (34,'fault_syn-sedimentary_inf','FAULT_TRACE','fault_syn-sedimentary_inf','fault_syn-sedimentary_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (35,'fault_thrust_inf_','FAULT_TRACE','fault_thrust_inf_','fault_thrust_inf_','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (36,'fault_thrust_obs','FAULT_TRACE','fault_thrust_obs','fault_thrust_obs','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (37,'fault_undifferentiated_inf','FAULT_TRACE','fault_undifferentiated_inf','fault_undifferentiated_inf','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (38,'fish_bed','BEDROCK_LINE','fish_bed','fish_bed','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (39,'fold_anticline','FOLD_AXIAL_PLANE_TRACE','fold_anticline','fold_anticline','deformation phase, name',NULL,'C','KIGL','21/11/2023 14:55:44',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (40,'fold_anticline_syncline_pair','FOLD_AXIAL_PLANE_TRACE','fold_anticline_syncline_pair','fold_anticline_syncline_pair','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (41,'fold_antiform','FOLD_AXIAL_PLANE_TRACE','fold_antiform','fold_antiform','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (42,'fold_antiform_synform_pair','FOLD_AXIAL_PLANE_TRACE','fold_antiform_synform_pair','fold_antiform_synform_pair','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (43,'fold_monocline_lower','FOLD_AXIAL_PLANE_TRACE','fold_monocline_lower','fold_monocline_lower','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (44,'fold_monocline_upper','FOLD_AXIAL_PLANE_TRACE','fold_monocline_upper','fold_monocline_upper','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (45,'fold_syncline','FOLD_AXIAL_PLANE_TRACE','fold_syncline','fold_syncline','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (46,'fold_synform','FOLD_AXIAL_PLANE_TRACE','fold_synform','fold_synform','none',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (47,'goniatite_band','BEDROCK_LINE','goniatite_band','goniatite_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (48,'gypsum_bed','BEDROCK_LINE','gypsum_bed','gypsum_bed','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (49,'ironstone_bed_inf','BEDROCK_LINE','ironstone_bed_inf','ironstone_bed_inf','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (50,'ironstone_bed_obs','BEDROCK_LINE','ironstone_bed_obs','ironstone_bed_obs','LEX, RCS (or ? LEX_RCS together),Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (51,'limestone_nodule_bed','BEDROCK_LINE','limestone_nodule_bed','limestone_nodule_bed','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (52,'limit_area_of_reddening','ALTERATION_BOUNDARY','limit_area_of_reddening','limit_area_of_reddening','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (53,'limit_diorite_granodiorite','ALTERATION_BOUNDARY','limit_diorite_granodiorite','limit_diorite_granodiorite','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (54,'limit_dolomitisation','ALTERATION_BOUNDARY','limit_dolomitisation','limit_dolomitisation','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (55,'limit_gran_peg_vein','ALTERATION_BOUNDARY','limit_gran_peg_vein','limit_gran_peg_vein','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (56,'limit_granite_vein','ALTERATION_BOUNDARY','limit_granite_vein','limit_granite_vein','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (57,'limit_halite','ALTERATION_BOUNDARY','limit_halite','limit_halite','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 15:01:11',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (58,'limit_hydrothermal_alteration','ALTERATION_BOUNDARY','limit_hydrothermal_alteration','limit_hydrothermal_alteration','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (59,'limit_metamorphic_aureole','ALTERATION_BOUNDARY','limit_metamorphic_aureole','limit_metamorphic_aureole','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (60,'limit_metamorphic_zone','ALTERATION_BOUNDARY','limit_metamorphic_zone','limit_metamorphic_zone','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (61,'limit_migmatisation','ALTERATION_BOUNDARY','limit_migmatisation','limit_migmatisation','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (62,'limit_pegmatite','ALTERATION_BOUNDARY','limit_pegmatite','limit_pegmatite','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (63,'lingula_band','BEDROCK_LINE','lingula_band','lingula_band','LEX, RCS, (or ? LEX_RCS together),Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (64,'lithostrat_line_other_inf','BEDROCK_LINE','lithostrat_line_other_inf','lithostrat_line_other_inf',NULL,NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (65,'lithostrat_line_other_obs','BEDROCK_LINE','lithostrat_line_other_obs','lithostrat_line_other_obs',NULL,NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (66,'magnetic_layer','BEDROCK_LINE','magnetic_layer','magnetic_layer','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (67,'manganese_bed','BEDROCK_LINE','manganese_bed','manganese_bed','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (68,'marine_band','BEDROCK_LINE','marine_band','marine_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (69,'mineral_vein_inf','MINERAL_VEIN_TRACE','mineral_vein_inf','mineral_vein_inf','mineral01, mineral02, mineral03, mineral04',NULL,'C','KIGL','21/11/2023 15:01:11',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (70,'mineral_vein_obs','MINERAL_VEIN_TRACE','mineral_vein_obs','mineral_vein_obs','mineral01, mineral02, mineral03, mineral04',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (71,'mussel_band','BEDROCK_LINE','mussel_band','mussel_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (72,'oil_shale_bed','BEDROCK_LINE','oil_shale_bed','oil_shale_bed','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (73,'planolites_band','BEDROCK_LINE','planolites_band','planolites_band','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (74,'sandstone_bed','BEDROCK_LINE','sandstone_bed','sandstone_bed','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (75,'zone_cataclasis_inf','ALTERATION_BOUNDARY','zone_cataclasis_inf','zone_cataclasis_inf','?',NULL,'C','KIGL','21/11/2023 15:45:39',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (76,'zone_cataclasis_obs','ALTERATION_BOUNDARY','zone_cataclasis_obs','zone_cataclasis_obs','?',NULL,'C','KIGL','21/11/2023 15:48:57',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (77,'zone_sheared_rock','ALTERATION_BOUNDARY','zone_sheared_rock','zone_sheared_rock','?',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'gull','MASS_MOVEMENT_LINE','gull','gull',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'landslide_back_scar_Top','MASS_MOVEMENT_LINE','landslide_back_scar_Top','landslide_back_scar_Top','asymmetry perendicular','barbs point into landslide','C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'landslide_lower_or_side_limit','MASS_MOVEMENT_LINE','landslide_lower_or_side_limit','landslide_lower_or_side_limit',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'landslide_minor_scarps','MASS_MOVEMENT_LINE','landslide_minor_scarps','landslide_minor_scarps',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'mass_move_geology_boundary','MASS_MOVEMENT_DEPOSIT_BOUNDARY','mass_move_geology_boundary','mass_move_geology_boundary',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'mass_move_polygon_closure','MASS_MOVEMENT_DEPOSIT_BOUNDARY','mass_move_polygon_closure','mass_move_polygon_closure',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'open_tension_crack_crossmark','MASS_MOVEMENT_LINE','open_tension_crack_crossmark','open_tension_crack_crossmark',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (8,'open_tension_crack_undiff','MASS_MOVEMENT_LINE','open_tension_crack_undiff','open_tension_crack_undiff',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'valley_bulge_axis_Inf','MASS_MOVEMENT_LINE','valley_bulge_axis_Inf','valley_bulge_axis_Inf',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'axis_of_glacial_flute','LINEAR_LANDFORM_OR_BEDFORM','axis_of_glacial_flute','axis_of_glacial_flute',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'axis_of_large_scale_glacial_gouge','LINEAR_LANDFORM_OR_BEDFORM','axis_of_large_scale_glacial_gouge','axis_of_large_scale_glacial_gouge',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'axis_of_megagroove','LINEAR_LANDFORM_OR_BEDFORM','axis_of_megagroove','axis_of_megagroove',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'axis_of_swale','LINEAR_LANDFORM_OR_BEDFORM','axis_of_swale','axis_of_swale',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'backfeature_Former_coast','LINEAR_LANDFORM_OR_BEDFORM','backfeature_Former_coast','backfeature_Former_coast','asymmetry perpendicular to line','arrowheads denote uphill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'backfeature_Lake_margin','LINEAR_LANDFORM_OR_BEDFORM','backfeature_Lake_margin','backfeature_Lake_margin','asymmetry perpendicular to line','arrowheads denote uphill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'backfeature_terrace','LINEAR_LANDFORM_OR_BEDFORM','backfeature_terrace','backfeature_terrace','asymmetry perpendicular to line','arrowheads denote uphill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (8,'beach_ridge','LINEAR_LANDFORM_OR_BEDFORM','beach_ridge','beach_ridge','asymmetry perpendicular to line','check','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'buried_channel_centre','LINEAR_LANDFORM_OR_BEDFORM','buried_channel_centre','buried_channel_centre','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (10,'buried_channel_margin','LINEAR_LANDFORM_OR_BEDFORM','buried_channel_margin','buried_channel_margin','asymmetry perpendicular to line','beads to outside','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (11,'cliffline_buried','LINEAR_LANDFORM_OR_BEDFORM','cliffline_buried','cliffline_buried','asymmetry perpendicular to line','crossmarks on the eroded side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (12,'cliffline_natural','LINEAR_LANDFORM_OR_BEDFORM','cliffline_natural','cliffline_natural','asymmetry perpendicular to line','crossmarks on the eroded side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (13,'crag_and_tail','LINEAR_LANDFORM_OR_BEDFORM','crag_and_tail','crag_and_tail','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (14,'doline_or_karstic_hollow','LINEAR_LANDFORM_OR_BEDFORM','doline_or_karstic_hollow','doline_or_karstic_hollow',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (15,'drumlin_crestline','LINEAR_LANDFORM_OR_BEDFORM','drumlin_crestline','drumlin_crestline',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (16,'drumlin_line_at_base','LINEAR_LANDFORM_OR_BEDFORM','drumlin_line_at_base','drumlin_line_at_base',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (17,'dune_crestline','LINEAR_LANDFORM_OR_BEDFORM','dune_crestline','dune_crestline',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (18,'dune_line_at_base','LINEAR_LANDFORM_OR_BEDFORM','dune_line_at_base','dune_line_at_base',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (19,'elongate_mound_crestline','LINEAR_LANDFORM_OR_BEDFORM','elongate_mound_crestline','elongate_mound_crestline',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (20,'esker_crestline','LINEAR_LANDFORM_OR_BEDFORM','esker_crestline','esker_crestline',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (21,'esker_line_at_base','LINEAR_LANDFORM_OR_BEDFORM','esker_line_at_base','esker_line_at_base',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (22,'glacial_meltwater_channel_centre_undiff','LINEAR_LANDFORM_OR_BEDFORM','glacial_meltwater_channel_centre_undiff','glacial_meltwater_channel_centre_undiff','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (23,'glacial_meltwater_channel_margin','LINEAR_LANDFORM_OR_BEDFORM','glacial_meltwater_channel_margin','glacial_meltwater_channel_margin',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (24,'glacial_overflow_channel_centre','LINEAR_LANDFORM_OR_BEDFORM','glacial_overflow_channel_centre','glacial_overflow_channel_centre','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (25,'ice_contact_slope','LINEAR_LANDFORM_OR_BEDFORM','ice_contact_slope','ice_contact_slope',' asymmetry perpendicular to line','CHECK hachure on upslope','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (26,'ice_marg_glacial_meltwater_channel_Left','LINEAR_LANDFORM_OR_BEDFORM','ice_marg_glacial_meltwater_channel_Left','ice_marg_glacial_meltwater_channel_Left','asymmetry linear, asymmetry perpendicular to line','barb on opposite side to ice, towards carved terrain','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (27,'ice_marg_glacial_meltwater_channel_Right','LINEAR_LANDFORM_OR_BEDFORM','ice_marg_glacial_meltwater_channel_Right','ice_marg_glacial_meltwater_channel_Right','asymmetry linear, asymmetry perpendicular to line','barb on opposite side to ice, towards carved terrain','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (28,'kettle_hole','LINEAR_LANDFORM_OR_BEDFORM','kettle_hole','kettle_hole',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (29,'limestone_fissures','LINEAR_LANDFORM_OR_BEDFORM','limestone_fissures','limestone_fissures','asymmetry linear, asymmetry perpendicular to line',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (30,'margin_of_erratic_train','LINEAR_LANDFORM_OR_BEDFORM','margin_of_erratic_train','margin_of_erratic_train',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (31,'moraine_crestline','LINEAR_LANDFORM_OR_BEDFORM','moraine_crestline','moraine_crestline','asymmetry perpendicular to line','ticks on former ice sheet side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (32,'mound_line_at_base','LINEAR_LANDFORM_OR_BEDFORM','mound_line_at_base','mound_line_at_base',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (33,'outer_edge_of_terrace','LINEAR_LANDFORM_OR_BEDFORM','outer_edge_of_terrace','outer_edge_of_terrace','asymmetry perpendicular to line','arrowheads denote uphill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (34,'palaeochannel','LINEAR_LANDFORM_OR_BEDFORM','palaeochannel','palaeochannel','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (35,'roche_moutonee_crestline','LINEAR_LANDFORM_OR_BEDFORM','roche_moutonee_crestline','roche_moutonee_crestline','asymmetry linear','arrow denotes flow of ice','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (36,'rogen_line_at_base','LINEAR_LANDFORM_OR_BEDFORM','rogen_line_at_base','rogen_line_at_base','asymmetry perpendicular to line','form line at base','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (37,'rogen_moraine_crestline','LINEAR_LANDFORM_OR_BEDFORM','rogen_moraine_crestline','rogen_moraine_crestline',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (38,'sea_bank','LINEAR_LANDFORM_OR_BEDFORM','sea_bank','sea_bank',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (39,'solifluction_lobe','LINEAR_LANDFORM_OR_BEDFORM','solifluction_lobe','solifluction_lobe',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (40,'stream_sink_line','LINEAR_LANDFORM_OR_BEDFORM','stream_sink_line','stream_sink_line',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (41,'sub-glacial_meltwater_channel_centre','LINEAR_LANDFORM_OR_BEDFORM','sub-glacial_meltwater_channel_centre','sub-glacial_meltwater_channel_centre','asymmetry linear','CHECK ?direction of flow','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (42,'subsidence_hollow','LINEAR_LANDFORM_OR_BEDFORM','subsidence_hollow','subsidence_hollow',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (43,'superficial_filled_hollow','LINEAR_LANDFORM_OR_BEDFORM','superficial_filled_hollow','superficial_filled_hollow',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (44,'thrust_in_superficial_Inf','LINEAR_LANDFORM_OR_BEDFORM','thrust_in_superficial_Inf','thrust_in_superficial_Inf','asymmetry perpendicular to line','barbs within mass','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (45,'tunnel_valley_centre','LINEAR_LANDFORM_OR_BEDFORM','tunnel_valley_centre','tunnel_valley_centre','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (46,'tunnel_valley_margin','LINEAR_LANDFORM_OR_BEDFORM','tunnel_valley_margin','tunnel_valley_margin','asymmetry linear',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'air_photo_lineament','TERRAIN_LINE','air_photo_lineament','air_photo_lineament',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'concave_break_of_slope','TERRAIN_LINE','concave_break_of_slope','concave_break_of_slope','asymmetry perpendicular to line','arrowheads denote uphill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'convex_break_of_slope','TERRAIN_LINE','convex_break_of_slope','convex_break_of_slope','asymmetry perpendicular to line','arrowheads denote downhill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'dtm_lineament','TERRAIN_LINE','dtm_lineament','dtm_lineament',NULL,NULL,'C','KIGL','8/12/2023 15:23:50',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'form_line','TERRAIN_LINE','form_line','form_line','asymmetry perpendicular to line',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'form_line_indicating_slope','TERRAIN_LINE','form_line_indicating_slope','form_line_indicating_slope','asymmetry perpendicular to line',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'hollow_margin','TERRAIN_LINE','hollow_margin','hollow_margin','asymmetry perpendicular to line','hachures point into hollow','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (8,'linear_negative_feature','TERRAIN_LINE','linear_negative_feature','linear_negative_feature',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'linear_positive_Feature_crestline','TERRAIN_LINE','linear_positive_Feature_crestline','linear_positive_Feature_crestline',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
COMMIT;