-- Dictionaries used to constrain line features.
BEGIN TRANSACTION;

CREATE TABLE "dic_line_type_artificial" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
    "status"	TEXT,
 	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_artificial','attributes','dic_line_type_artificial','Dictionary of artificial line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_bedrock" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
    "description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
    "status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_bedrock','attributes','dic_line_type_bedrock','Dictionary of bedrock line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_superficial" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
    "comments" TEXT,
	"status"	TEXT,
    "sec_attrib_list"  TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_superficial','attributes','dic_line_type_superficial','Dictionary of superficial line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_mass_move" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_mass_move','attributes','dic_line_type_mass_move','Dictionary of mass movement line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

CREATE TABLE "dic_line_type_terrain" (
	"fid"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL UNIQUE,
	"category" TEXT,
	"description"	TEXT,
	"translation"	TEXT,
	"sec_attrib_list"  TEXT,
    "comments" TEXT,
	"status"	TEXT,
	"user_entered"	TEXT NOT NULL,
	"date_entered"	DATETIME NOT NULL,
	"user_updated"	TEXT,
	"date_updated"	DATETIME,
	PRIMARY KEY("fid" AUTOINCREMENT)
);

insert into gpkg_contents
values('dic_line_type_terrain','attributes','dic_line_type_terrain','Dictionary of terrain line types','2023-09-15t13:21:52.679z',null,null,null,null,null);

INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'artificial_geology_boundary','ARTIFICIAL_GROUND_BOUNDARY','artificial_geology_boundary','','none yet',NULL,'C','KIGL','26/11/2023 12:16:00',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'artificial_polygon_closure','ARTIFICIAL_GROUND_BOUNDARY','artificial_polygon_closure','','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'cliffline_quarry','ARTIFICIAL_GROUND_LINE','cliffline_quarry','','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'limit_subsurface_mining','ARTIFICIAL_GROUND_LINE_UNDERGROUND','limit_subsurface_mining','','none yet','ArcPro Compilation','C','KIGL','26/11/2023 12:17:38','JBOW','09/05/2024');
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'mine_tunnel_drift_cross_measures','ARTIFICIAL_GROUND_LINE_UNDERGROUND','mine_tunnel_drift_cross_measures','','none yet','ArcPro Compilation','C','KIGL','26/11/2023 12:17:38','JBOW','09/05/2024');
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'mine_tunnel_road_in seam','ARTIFICIAL_GROUND_LINE_UNDERGROUND','mine_tunnel_road_in seam','','none yet','ArcPro Compilation','C','KIGL','26/11/2023 12:17:38','JBOW','09/05/2024');
INSERT INTO "dic_line_type_artificial" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'small_quarry_or_pit','ARTIFICIAL_GROUND_LINE','small_quarry_or_pit','','none yet',NULL,'C','KIGL','26/11/2023 12:17:38',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'algal_band','BEDROCK_HORIZON','algal_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'ash_band_tonstein','BEDROCK_HORIZON','ash_band_tonstein','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'base_of_lava_flow','BEDROCK_HORIZON','base_of_lava_flow','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'bedrock_geology_boundary_grad','BEDROCK_BOUNDARY','bedrock_geology_boundary_grad','','none',NULL,'C','KIGL','21/11/2023 14:52:25',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'bedrock_geology_boundary_inf','BEDROCK_BOUNDARY','bedrock_geology_boundary_inf','','none',NULL,'C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'bedrock_geology_boundary_obs','BEDROCK_BOUNDARY','bedrock_geology_boundary_obs','','none',NULL,'C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'bedrock_offshore_closure','BEDROCK_BOUNDARY','bedrock_offshore_closure','','none',NULL,'C','KIGL','21/11/2023 15:51:03',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (8,'bedrock_polygon_closure','BEDROCK_BOUNDARY','bedrock_polygon_closure','','none',NULL,'C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'bone_bed','BEDROCK_HORIZON','bone_bed','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (10,'brachiopod_band','BEDROCK_HORIZON','brachiopod_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (11,'cementstone_bed','BEDROCK_HORIZON','cementstone_bed','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (12,'coal_seam_inf','BEDROCK_HORIZON','coal_seam_inf','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (13,'coal_seam_obs','BEDROCK_HORIZON','coal_seam_obs','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (14,'coral_band','BEDROCK_HORIZON','coral_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (15,'ductile_shear_inf','FAULT_TRACE','ductile_shear_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (16,'ductile_shear_obs','FAULT_TRACE','ductile_shear_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (17,'dyke_inf','DYKE','dyke_inf','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (18,'dyke_obs','DYKE','dyke_obs','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (19,'euestheria_band','BEDROCK_HORIZON','euestheria_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (20,'fault_complex_movenent_inf','FAULT_TRACE','fault_complex_movenent_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (21,'fault_complex_movenent_obs','FAULT_TRACE','fault_complex_movenent_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (22,'fault_dextral_inf','FAULT_TRACE','fault_dextral_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:52:51',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (23,'fault_dextral_obs','FAULT_TRACE','fault_dextral_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (24,'fault_crossmark_downthrow_side_inf','FAULT_TRACE','fault_crossmark_downthrow_side_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (25,'fault_throw_unknown_inf','FAULT_TRACE','fault_throw_unknown_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (26,'fault_normal_inf','FAULT_TRACE','fault_normal_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (27,'fault_normal_obs','FAULT_TRACE','fault_normal_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (28,'fault_crossmark_downthrow_side_obs','FAULT_TRACE','fault_crossmark_downthrow_side_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (29,'fault_throw_unknown_obs','FAULT_TRACE','fault_throw_unknown_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (30,'fault_reverse_inf','FAULT_TRACE','fault_reverse_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (31,'fault_reverse_obs','FAULT_TRACE','fault_reverse_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (32,'fault_sinistral_inf','FAULT_TRACE','fault_sinistral_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (33,'fault_sinistral_obs','FAULT_TRACE','fault_sinistral_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (34,'fault_syn-sedimentary_inf','FAULT_TRACE','fault_syn-sedimentary_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (35,'fault_thrust_inf','FAULT_TRACE','fault_thrust_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (36,'fault_thrust_obs','FAULT_TRACE','fault_thrust_obs','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (37,'fault_undifferentiated_inf','FAULT_TRACE','fault_undifferentiated_inf','','hanging wall direction, name','check for left hand rule and alter if necessary','C','KIGL','21/11/2023 14:55:04',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (38,'fish_bed','BEDROCK_HORIZON','fish_bed','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (39,'anticline','FOLD_TRACE','fold_anticline','','deformation phase, name',NULL,'C','KIGL','21/11/2023 14:55:44','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (40,'anticline_syncline_pair','FOLD_TRACE','fold_anticline_syncline_pair','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (41,'antiform','FOLD_TRACE','fold_antiform','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (42,'antiform_synform_pair','FOLD_TRACE','fold_antiform_synform_pair','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (43,'monocline_lower','FOLD_TRACE','fold_monocline_lower','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (44,'monocline_upper','FOLD_TRACE','fold_monocline_upper','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (45,'syncline','FOLD_TRACE','fold_syncline','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (46,'synform','FOLD_TRACE','fold_synform','','none',NULL,'C','KIGL','21/11/2023 14:56:26','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (47,'goniatite_band','BEDROCK_HORIZON','goniatite_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (48,'gypsum_bed','BEDROCK_HORIZON','gypsum_bed','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (49,'ironstone_bed_inf','BEDROCK_HORIZON','ironstone_bed_inf','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (50,'ironstone_bed_obs','BEDROCK_HORIZON','ironstone_bed_obs','','LEX, RCS (or ? LEX_RCS together),Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (51,'limestone_nodule_bed','BEDROCK_HORIZON','limestone_nodule_bed','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (52,'limit_area_of_reddening','ALTERATION_BOUNDARY','limit_area_of_reddening','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (53,'limit_diorite_granodiorite','ALTERATION_BOUNDARY','limit_diorite_granodiorite','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (54,'limit_dolomitisation','ALTERATION_BOUNDARY','limit_dolomitisation','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (55,'limit_gran_pegmatite_vein','ALTERATION_BOUNDARY','limit_gran_pegmatite_vein','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (56,'limit_granite_vein','ALTERATION_BOUNDARY','limit_granite_vein','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (57,'limit_halite','ALTERATION_BOUNDARY','limit_halite','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 15:01:11',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (58,'limit_hydrothermal_alteration','ALTERATION_BOUNDARY','limit_hydrothermal_alteration','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (59,'limit_metamorphic_aureole','ALTERATION_BOUNDARY','limit_metamorphic_aureole','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (60,'limit_metamorphic_zone','ALTERATION_BOUNDARY','limit_metamorphic_zone','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (61,'limit_migmatisation','ALTERATION_BOUNDARY','limit_migmatisation','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (62,'limit_pegmatite','ALTERATION_BOUNDARY','limit_pegmatite','','mineral, asymmetry ticks,',NULL,'C','KIGL','21/11/2023 14:50:19',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (63,'lingula_band','BEDROCK_HORIZON','lingula_band','','LEX, RCS, (or ? LEX_RCS together),Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (64,'lithostrat_line_other_inf','BEDROCK_HORIZON','lithostrat_line_other_inf','',NULL,NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (65,'lithostrat_line_other_obs','BEDROCK_HORIZON','lithostrat_line_other_obs','',NULL,NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (66,'magnetic_layer','BEDROCK_HORIZON','magnetic_layer','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (67,'manganese_bed','BEDROCK_HORIZON','manganese_bed','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (68,'marine_band','BEDROCK_HORIZON','marine_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (69,'mineral_vein_inf','MINERAL_VEIN_TRACE','mineral_vein_inf','','mineral01, mineral02, mineral03, mineral04',NULL,'C','KIGL','21/11/2023 15:01:11',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (70,'mineral_vein_obs','MINERAL_VEIN_TRACE','mineral_vein_obs','','mineral01, mineral02, mineral03, mineral04',NULL,'C','KIGL','21/11/2023 14:56:26',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (71,'mussel_band','BEDROCK_HORIZON','mussel_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (72,'oil_shale_bed','BEDROCK_HORIZON','oil_shale_bed','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (73,'planolites_band','BEDROCK_HORIZON','planolites_band','','LEX, RCS (or ? LEX_RCS together), Younging',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (74,'sandstone_bed','BEDROCK_HORIZON','sandstone_bed','','LEX, RCS (or ? LEX_RCS together)',NULL,'C','KIGL','21/11/2023 14:47:49','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (75,'limit_zone_cataclasis','ALTERATION_BOUNDARY','limit_zone_cataclasis','','?',NULL,'C','KIGL','21/11/2023 15:45:39','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (77,'limit_zone_sheared_rock','ALTERATION_BOUNDARY','limit_zone_sheared_rock','','?',NULL,'C','KIGL','21/11/2023 14:50:19','JBOW','09/05/2024');
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (78,'bedrock_geology_boundary_conj','BEDROCK_BOUNDARY','bedrock_geology_boundary_conj',NULL,NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (79,'bedrock_boundary_underground','BEDROCK_HORIZON_UNDERGROUND','bedrock_boundary_underground',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (80,'incrop_coal','BEDROCK_HORIZON_UNDERGROUND','incrop_coal',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (81,'incrop_marine_band','BEDROCK_HORIZON_UNDERGROUND','incrop_marine_band',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (82,'bedrock_boundary_subpermian','BEDROCK_HORIZON_UNDERGROUND','bedrock_boundary_subpermian',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (83,'coal_boundary_subpermian','BEDROCK_HORIZON_UNDERGROUND','coal_boundary_subpermian',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (84,'coal_subtriassic','BEDROCK_HORIZON_UNDERGROUND','coal_subtriassic',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (85,'washout_in_coalseam','BEDROCK_HORIZON_UNDERGROUND','washout_in_coalseam',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (86,'dyke_inf_underground
','DYKE_UNDERGROUND','dyke_inf_underground',NULL,'LEX, RCS (or ? LEX_RCS together)','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (87,'fault_conjectural','FAULT_TRACE','fault_conjectural',NULL,'name',NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (88,'incrop_fault','FAULT_TRACE_UNDERGROUND','incrop_fault',NULL,'name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (89,'subpermian_fault_inf','FAULT_TRACE_UNDERGROUND','subpermian_fault_inf',NULL,'hanging wall direction, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (90,'subtriassic_fault_inf','FAULT_TRACE_UNDERGROUND','subtriassic_fault_inf',NULL,'hanging wall direction, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (91,'fault_inf_underground','FAULT_TRACE_UNDERGROUND','fault_inf_underground',NULL,'name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (92,'fault_crossmark_downthrow_side_inf_underground','FAULT_TRACE_UNDERGROUND','fault_crossmark_downthrow_side_inf_underground',NULL,'hanging wall direction, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (93,'fault_throw_unknown_inf_underground','FAULT_TRACE_UNDERGROUND','fault_throw_unknown_inf_underground',NULL,'name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (94,'fault_obs_underground','FAULT_TRACE_UNDERGROUND','fault_obs_underground',NULL,'name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (95,'fault_crossmark_downthrow_side_obs_underground','FAULT_TRACE_UNDERGROUND','fault_crossmark_downthrow_side_obs_underground',NULL,'hanging wall direction, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (96,'fault_obs_downthrow_unspecified_obs_underground','FAULT_TRACE_UNDERGROUND','fault_obs_downthrow_unspecified_obs_underground',NULL,'hanging wall direction, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (97,'fracture_inf','FRACTURE_TRACE','fracture_inf',NULL,NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (98,'fracture_obs','FRACTURE_TRACE','fracture_obs',NULL,NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (99,'anticline_underground','FOLD_TRACE_UNDERGROUND','anticline_underground',NULL,'deformation phase, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (100,'syncline_underground','FOLD_TRACE_UNDERGROUND','syncline_underground',NULL,'deformation phase, name','ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (101,'mineral_vein_obs_underground','MINERAL_VEIN_TRACE_UNDERGROUND','mineral_vein_obs_underground',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (102,'mineral_vein_inf_underground','MINERAL_VEIN_TRACE_UNDERGROUND','mineral_vein_inf_underground',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (103,'unconformity_major','UNCONFORMITY','unconformity_major',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_bedrock" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (104,'unconformity_minor','UNCONFORMITY','unconformity_minor',NULL,NULL,'ArcPro Compilation','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (1,'axis_of_glacial_flute','GLACIAL_LANDFORM','axis_of_glacial_flute','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (2,'axis_of_large_scale_glacial_gouge','GLACIAL_LANDFORM','axis_of_large_scale_glacial_gouge','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (3,'axis_of_megagroove','GLACIAL_LANDFORM','axis_of_megagroove','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (4,'axis_of_swale','GLACIAL_LANDFORM','axis_of_swale','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (5,'backfeature_former_coast','LANDFORM_GENERAL','backfeature_former_coast','','arrowheads denote uphill side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (6,'backfeature_lake_margin','LANDFORM_GENERAL','backfeature_lake_margin','','arrowheads denote uphill side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (7,'backfeature_terrace','LANDFORM_GENERAL','backfeature_terrace','','arrowheads denote uphill side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (8,'beach_ridge','LANDFORM_GENERAL','beach_ridge','','check','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (9,'buried_channel_centre','LANDFORM_GENERAL','buried_channel_centre','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (10,'buried_channel_margin','LANDFORM_GENERAL','buried_channel_margin','','beads to outside','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (11,'cliffline_buried','LANDFORM_GENERAL','cliffline_buried','','crossmarks on the eroded side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (12,'cliffline_natural','LANDFORM_GENERAL','cliffline_natural','','crossmarks on the eroded side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (13,'crag_and_tail','GLACIAL_LANDFORM','crag_and_tail','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (14,'doline_or_karstic_hollow','KARSTIC_LANDFORM','doline_or_karstic_hollow','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (15,'drumlin_crestline','GLACIAL_LANDFORM','drumlin_crestline','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (16,'drumlin_line_at_base','GLACIAL_LANDFORM','drumlin_line_at_base','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (17,'dune_crestline','LANDFORM_GENERAL','dune_crestline','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (18,'dune_line_at_base','LANDFORM_GENERAL','dune_line_at_base','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (19,'elongate_mound_crestline','GLACIAL_LANDFORM','elongate_mound_crestline','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (20,'esker_crestline','GLACIAL_LANDFORM','esker_crestline','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (21,'esker_line_at_base','GLACIAL_LANDFORM','esker_line_at_base','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (22,'glacial_meltwater_channel_centre_undiff','GLACIAL_LANDFORM','glacial_meltwater_channel_centre_undiff','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (23,'glacial_meltwater_channel_margin','GLACIAL_LANDFORM','glacial_meltwater_channel_margin','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (24,'glacial_overflow_channel_centre','GLACIAL_LANDFORM','glacial_overflow_channel_centre','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (25,'ice_contact_slope','GLACIAL_LANDFORM','ice_contact_slope','','CHECK hachure on upslope','C',' asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (26,'ice_marg_glacial_meltwater_channel_left','GLACIAL_LANDFORM','ice_marg_glacial_meltwater_channel_left','','barb on opposite side to ice, towards carved terrain','C','asymmetry linear, asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (27,'ice_marg_glacial_meltwater_channel_right','GLACIAL_LANDFORM','ice_marg_glacial_meltwater_channel_right','','barb on opposite side to ice, towards carved terrain','C','asymmetry linear, asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (28,'kettle_hole','GLACIAL_LANDFORM','kettle_hole','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (29,'limestone_fissures','KARSTIC_LANDFORM','limestone_fissures','',NULL,'C','asymmetry linear, asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (30,'margin_of_erratic_train','GLACIAL_LANDFORM','margin_of_erratic_train','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (31,'moraine_crestline','GLACIAL_LANDFORM','moraine_crestline','','ticks on former ice sheet side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (32,'mound_line_at_base','GLACIAL_LANDFORM','mound_line_at_base','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (33,'outer_edge_of_terrace','LANDFORM_GENERAL','outer_edge_of_terrace','','arrowheads denote uphill side','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (34,'palaeochannel','LANDFORM_GENERAL','palaeochannel','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (35,'roche_moutonee_crestline','GLACIAL_LANDFORM','roche_moutonee_crestline','','arrow denotes flow of ice','C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (36,'rogen_line_at_base','GLACIAL_LANDFORM','rogen_line_at_base','','form line at base','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (37,'rogen_moraine_crestline','GLACIAL_LANDFORM','rogen_moraine_crestline','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (38,'sea_bank','LANDFORM_GENERAL','sea_bank','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (40,'stream_sink_line','KARSTIC_LANDFORM','stream_sink_line','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (41,'sub-glacial_meltwater_channel_centre','GLACIAL_LANDFORM','sub-glacial_meltwater_channel_centre','','CHECK ?direction of flow','C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (42,'subsidence_hollow','LANDFORM_GENERAL','subsidence_hollow','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (43,'superficial_filled_hollow','LANDFORM_GENERAL','superficial_filled_hollow','',NULL,'C',NULL,'KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (44,'thrust_in_superficial_inf','GLACIAL_LANDFORM','thrust_in_superficial_inf','','barbs within mass','C','asymmetry perpendicular to line','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (45,'tunnel_valley_centre','GLACIAL_LANDFORM','tunnel_valley_centre','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (46,'tunnel_valley_margin','GLACIAL_LANDFORM','tunnel_valley_margin','',NULL,'C','asymmetry linear','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (47,'superficial_geology_boundary','SUPERFICIAL_DEPOSIT_BOUNDARY','superficial_geology_boundary',NULL,NULL,'C',NULL,'JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (48,'superficial_polygon_closure','SUPERFICIAL_DEPOSIT_BOUNDARY','superficial_polygon_closure',NULL,NULL,'C',NULL,'JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (49,'glacial_limit_inf','QUATERNARY_LIMITS','glacial_limit_inf',NULL,'ArcPro Compilation','C','NAME; asymmetry perpendicular to line','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (50,'glacial_limit_uncertain','QUATERNARY_LIMITS','glacial_limit_uncertain',NULL,'ArcPro Compilation','C','NAME; asymmetry perpendicular to line','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (51,'limit_glacial_lake_inf','QUATERNARY_LIMITS','limit_glacial_lake_inf',NULL,'ArcPro Compilation','C','NAME; asymmetry perpendicular to line','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_superficial" ("fid","code","category","description","translation","comments","status","sec_attrib_list","user_entered","date_entered","user_updated","date_updated") VALUES (52,'limit_marine_incursion_inf','QUATERNARY_LIMITS','limit_marine_incursion_inf',NULL,'ArcPro Compilation','C','NAME; asymmetry perpendicular to line','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'gull_undiff','MASS_MOVEMENT_LINE','gull_undiff','',NULL,NULL,'C','KIGL','26/11/2023 12:12:31','JBOW','09/05/2024');
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'landslide_main_scarp','MASS_MOVEMENT_LINE','landslide_main_scarp','','asymmetry perendicular','barbs point into landslide','C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'landslide_head_zone_limit','MASS_MOVEMENT_LINE','landslide_head_zone_limit','',NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'landslide_minor_scarp','MASS_MOVEMENT_LINE','landslide_minor_scarp','',NULL,NULL,'C','KIGL','26/11/2023 12:12:31','JBOW','09/05/2024');
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'mass_move_geology_boundary','MASS_MOVEMENT_DEPOSIT_BOUNDARY','mass_move_geology_boundary','',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'mass_move_polygon_closure','MASS_MOVEMENT_DEPOSIT_BOUNDARY','mass_move_polygon_closure','',NULL,NULL,'C','KIGL','26/11/2023 12:12:31',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'tension_crack','MASS_MOVEMENT_LINE','tension_crack','',NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'valley_bulge_axis_inf','MASS_MOVEMENT_LINE','valley_bulge_axis_inf','',NULL,NULL,'C','KIGL','26/11/2023 12:12:31','JBOW','09/05/2024');
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (10,'solifluction_lobe','MASS_MOVEMENT_LINE','solifluction_lobe',NULL,NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_mass_move" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (11,'gully','MASS_MOVEMENT_LINE','gully',NULL,NULL,NULL,'C','JBOW','09/05/2024',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (1,'air_photo_lineament','TERRAIN_LINE','air_photo_lineament','',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (2,'concave_break_of_slope','TERRAIN_LINE','concave_break_of_slope','','asymmetry perpendicular to line','arrowheads denote uphill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (3,'convex_break_of_slope','TERRAIN_LINE','convex_break_of_slope','','asymmetry perpendicular to line','arrowheads denote downhill side','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (4,'dtm_lineament','TERRAIN_LINE','dtm_lineament','',NULL,NULL,'C','KIGL','8/12/2023 15:23:50',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (5,'form_line','TERRAIN_LINE','form_line','','asymmetry perpendicular to line',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (6,'form_line_indicating_slope','TERRAIN_LINE','form_line_indicating_slope','','asymmetry perpendicular to line',NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (7,'hollow_margin','TERRAIN_LINE','hollow_margin','','asymmetry perpendicular to line','hachures point into hollow','C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (8,'linear_negative_feature','TERRAIN_LINE','linear_negative_feature','',NULL,NULL,'C','KIGL','26/11/2023 11:47:04',NULL,NULL);
INSERT INTO "dic_line_type_terrain" ("fid","code","category","description","translation","sec_attrib_list","comments","status","user_entered","date_entered","user_updated","date_updated") VALUES (9,'linear_positive_feature_crestline','TERRAIN_LINE','linear_positive_feature_crestline','',NULL,NULL,'C','KIGL','26/11/2023 11:47:04','JBOW','09/05/2024');
COMMIT;