# Copyright 2026 UKRI / British Geological Survey
# Licensed under GPLv3 licence
# SPDX-License-Identifier: GPL-3.0-or-later
name: Lint and test

on:
  push:
    branches:
      - "*"
    paths:
      - 'CRAG/**'
      - 'test/**'
      - 'docs/user_guide/source'
      - 'environment*.yml'
      - '.github/workflows/lint_and_test.yml'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6

    - name: Cache conda environment
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0  # v5
      env:
        # Increase this value to reset cache if environment file has not changed
        CACHE_NUMBER: 1
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5  # v4.0.1
      with:
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: crag
        auto-activate-base: false
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      env:
        CONDA_OVERRIDE_ARCHSPEC: x86_64_v4

    - name: Lint
      shell: bash -l {0}
      run: flake8 CRAG/ test/ bin/

    - name: Test
      shell: bash -l {0}
      env:
        # This allows Qt to run headless.  It replaces the xvfb command
        # that we use in the Docker containers.
        QT_QPA_PLATFORM: offscreen
      run: |
        pytest -vv test/

    - name: Test Plugin Build
      env:
        # This allows Qt to run headless.  It replaces the xvfb command
        # that we use in the Docker containers.
        QT_QPA_PLATFORM: offscreen
        PYTHONUNBUFFERED: 1
      shell: bash -l {0}
      run: |
        cd CRAG
        python ../bin/update_plugin_metadata.py metadata.txt >> "$GITHUB_ENV"
        pb_tool zip
        cd zip_build
        python -c "from qgis.testing.mocked import get_iface; from crag import classFactory; classFactory(get_iface())"
